<?php 
	global $expArr,$eduArr,$degreeArr,$yearArr,$roleArr,$engLevelArr;
	$user =  $this->user_information ;
?>
<style type="text/css">
ul#info_ul span {
	color:#e35b5a;
	font-weight:bold;
}
.widget-wrap {
	min-height:auto
}
p{
	white-space:nowrap;
}
</style>

<div class="row">
    <div class="col-sm-12">
    <div class="page-header filled full-block light">
        <div class="row">
            <div class="col-md-6">
                <h2><?=$this->pageHeading?></h2>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
        <div class="col-md-4 PaddingZero">
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Profile Image</h3>
                    </div>
                </div>
                
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="content">
                                <p class="clearfix"></p>
                                <div class="form-group text-center"> 
                                    <img src="<?php echo getUserImage($user['user_image'],'160')?>" alt="" class="img-responsive img-thumbnail"/>
                                    <ul class="list-unstyled text-center">
                                        
                                        <li><?php echo $user['user_email']?></li>
                                    </ul>
                                </div>
                                 <hr />
                                <form method="POST" name="admin" class="profile_form"  novalidate="novalidate">
                               		<div class="form-group">
                                    <label class="form-label" for="">Prosperity</label>
								 	 <?= $this->formElement($form->get('user_prosperity'))?>
                                     </div>
                                     <div class="text-center">
                                     <?php echo $this->formElement($form->get('bttnsubmit'));?>
                                     </div>
                                  </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="col-md-8">
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Account Information</h3>
                    </div>
                </div>
                    
                <p class="clearfix"></p>
                    
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="form-content">
                                <table class="table table-striped table-hover table-bordered Clear" style="margin:0px !important;">
                                    <tbody>
                                        <tr>
                                            <td class="" width="30%;"><b>First Name:</b></td>
                                            <td><?=$this->user_information['user_first_name']?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td class="" width="30%;"><b>Last Name:</b></td>
                                            <td><?=$this->user_information['user_last_name']?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td class="" width="30%;"><b>Email:</b></td>
                                            <td><?=$this->user_information['user_email']?></td>
                                        </tr>
                                         <tr>
                                            <td class="" width="30%;"><b>Location:</b></td>
                                            <td><?=$this->user_information['user_location']?></td>
                                        </tr>
                                        <tr>
                                            <td class="" width="30%;"><b>Annual Income:</b></td>
                                            <td><?=PRICE_SYMBOL.$this->user_information['user_annual_income']?></td>
                                        </tr>
                                        
                                         <tr>
                                            <td class="" width="30%;"><b>Employment Status:</b></td>
                                            <td><?=$this->user_information['user_emp_status']=='1'?"Not Employed":"Currently Employed";?></td>
                                        </tr>
                                        <?php if($this->user_information['user_login_type']=='social'){?>
                                         <tr>
                                            <td class="" width="30%;"><b>Registered By:</b></td>
                                            <td>
                                            <?php if(strtolower($this->user_information['user_oauth_provider'])=='googleplus'){
													echo "Google";
											}else{?>
											<?=ucfirst($this->user_information['user_oauth_provider'])?>
											<? }?></td>
                                        </tr>
                                        
                                        <? }?>
                                        
                                        <tr>
                                            <td class="" width="30%;"><b>Primary reason for investing:</b></td>
                                            <td><?=$this->user_information['inv_res_title']?></td>
                                        </tr>
                                        <?php if($this->user_information['user_book_type']==5){?>
											<tr>
                                            <td class="" width="30%;"><b>Purchase is expected to be made:</b></td>
                                            <td><?=$this->user_information['inv_res_opt_restype']?></td>
                                        	</tr>
										<? }?>
                                        <tr>
                                            <td class="" width="30%;"><b>Currently investing</b></td>
                                            <td><?=$this->user_information['user_invest_opt']=='1'?"Yes":"No";?></td>
                                        </tr>
                                        <?php if($this->user_information['user_invest_opt']==1){?>
                                        <tr>
                                            <td class="" width="30%;"><b>How investing?</b></td>
                                            <td><?=$this->user_information['inv_ty_title'];?></td>
                                        </tr>
                                        <? }?>
                                        <tr>
                                            <td class="" width="30%;"><b>Investable assets</b></td>
                                            <td><?=PRICE_SYMBOL.$this->user_information['user_invest_assets'];?></td>
                                        </tr>
                                       
                                        <?php /*?><tr>
                                            <td class="" width="30%;"><b>Phone Number:</b></td>
                                            <td><?=$this->user_information['user_phoneno']!=''?$this->user_information['user_phoneno']:"N/A";?></td>
                                        </tr><?php */?>
                                         
                                       
                                    </tbody>
                                </table>
                                <hr />
                               
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Improvement Request</h3>
                    </div>
                </div>
                    
                <p class="clearfix"></p>
                    
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="form-content">
                                <table class="table table-striped table-hover table-bordered Clear" style="margin:0px !important;">
                                    <tbody>
                                   
                                        <tr>
                                            
                                            <td><?=$this->user_information['user_dashboard_txt']==''?"Not available":nl2br($this->user_information['user_dashboard_txt'])?></td>
                                        </tr>
                                         </tbody>
                                </table>
                                <hr />
                               
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
       
        
        
    </div>
</div>
