<div class="page-header filled full-block light">
	<h2><i><span class="<?php echo $this->page_icon ?>"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
</div>
  <div class="widget-wrap">
    <div class="widget-container">
      <div class="widget-content">
      <div id="flash-message" class="alert alert-dismissable" style="display:none; margin:20px;"></div>
   
        <form method="post" >
          
          <table id="sample_1" class="table table-striped table-bordered table-hover dataTable">
            <thead>
              <tr>
                <th width="5%">S.No.</th>
               
                <th>Photo</th>
                <th>Full Name</th>
                
                <th>Amount</th>
                 <th>Action</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </form>
      </div>
    </div>
  </div>

<script type="text/javascript" charset="utf-8">

$(document).ready(function(e) {
	var sortArr=[1,4];
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": false,
		"responsive": true,
 		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/getbalance" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": sortArr },
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnInitComplete": function (oSettings, json) { re_init();}
	} );
});


</script>