<?php 
	global $expArr,$eduArr,$degreeArr,$yearArr,$roleArr,$engLevelArr;
	$user =  $this->user_information ;
?>
<style type="text/css">
ul#info_ul span {
	color:#e35b5a;
	font-weight:bold;
}
.widget-wrap {
	min-height:auto
}
p{
	white-space:nowrap;
}

 .closed .vertical {
    transition: all 0.5s ease-in-out;
    transform: rotate(-90deg);
  }
  .closed .horizontal {
    transition: all 0.5s ease-in-out;
    transform: rotate(-90deg);
    opacity: 1;
  }


.opened {
  opacity: 1;
}
 .opened .vertical {
    transition: all 0.5s ease-in-out;
    transform: rotate(90deg);
  }
  .opened .horizontal {
    transition: all 0.5s ease-in-out;
    transform: rotate(90deg);
    opacity: 0;
  }


.circle-plus {
    height: 4em;
    width: 4em;
    font-size: 1em;
    opacity: .7;
}

.circle-plus .circle {
    position: relative;
    width: 2.55em;
    height: 2.5em;
    border-radius: 100%;
    border: solid .5em #DFDAD7;
}
.circle-plus .circle .horizontal {
    position: absolute;
    background-color: red;
    width: 30px;
    height: 5px;
    left: 50%;
    margin-left: -15px;
    top: 50%;
    margin-top: -2.5px;
}
.circle-plus .circle .vertical {
    position: absolute;
    background-color: red;
    width: 5px;
    height: 30px;
    left: 50%;
    margin-left: -2.5px;
    top: 50%;
    margin-top: -15px;
}


</style>

<div class="row">
    <div class="col-sm-12">
    <div class="page-header filled full-block light">
        <div class="row">
            <div class="col-md-6">
                <h2><?=$this->pageHeading?></h2>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
        <div class="col-md-4 PaddingZero">
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Profile Image</h3>
                    </div>
                </div>
                
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="content">
                                <p class="clearfix"></p>
                                <div class="form-group text-center"> 
                                    <img src="<?php echo getUserImage($user['user_image'],'160')?>" alt="" class="img-responsive img-thumbnail"/>
                                    <ul class="list-unstyled text-center">
                                        
                                        <li><?php echo $user['user_email']?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="col-md-8">
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Account Information</h3>
                    </div>
                </div>
                    
                <p class="clearfix"></p>
                    
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="form-content">
                                <table class="table table-striped table-hover table-bordered Clear" style="margin:0px !important;">
                                    <tbody>
                                        <tr>
                                            <td class="" width="30%;"><b>First Name:</b></td>
                                            <td><?=$this->user_information['user_first_name']?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td class="" width="30%;"><b>Last Name:</b></td>
                                            <td><?=$this->user_information['user_last_name']?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td class="" width="30%;"><b>Email:</b></td>
                                            <td><?=$this->user_information['user_email']?></td>
                                        </tr>
                                        
                                        <tr>
                                            <td class="" width="30%;"><b>Balance:</b></td>
                                            <td><?=PRICE_SYMBOL.$this->user_information['user_balance']?></td>
                                        </tr>
                                        
                                         
                                       
                                        
                                       
                                        
                                       
                                       
                                       
                                         
                                       
                                    </tbody>
                                </table>
                                <hr />
                               
                               
                               	<form method="POST" name="admin" class="profile_form" id="admin" novalidate="novalidate">
                                	<div style="display:inline-block;vertical-align: bottom;" >
                                            <div class="circle-plus closed" title="Add" >
                                                  <div class="circle">
                                                    <div class="horizontal"></div>
                                                    <div class="vertical"></div>
                                                  </div>
                               			 </div>
                               		 </div>
                                 <div class="form-group" style="display:inline-block;width:90%;">
                                 
                                  <label class="form-label" for="">Balance(<?php echo PRICE_SYMBOL?>)</label>
								  <?= $this->formElement($form->get('user_amount'))?>
                                  <?= $this->formElement($form->get('user_action'))?>
                                  
                                  </div>
									<div class="clearfix"></div>
									<div class="text-center"><button type="submit" class="btn site-btn SiteButton">Submit</button></div>
						</form>
                               <?php /*?><?php echo $this->renderForm($this->form);?> <?php */?>
                               
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Balance</h3>
                    </div>
                </div>
                    
                <p class="clearfix"></p>
                    
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="form-content">
                                <table class="table table-striped table-hover table-bordered Clear" style="margin:0px !important;">
                                    <tbody>
                                    	<?php if(!empty($this->users_balance)){
											?>
											
											 <tr>
                                            
                                            <td>Balance</td>
                                            <td>Action</td>
                                            <td>Balance On</td>
                                       		 </tr>
											<? foreach($this->users_balance as $user_k=>$user_val){ 
											?>
											 <tr>
                                            
                                            <td><?=PRICE_SYMBOL.$user_val['user_bal_balance']?></td>
                                            <td><?=$user_val['user_bal_type']==0?"Credit":"Debit"?></td>
                                            <td><?=date("d/m/Y",strtotime($user_val['user_bal_addedon']))?></td>
                                        </tr>
                                        	<? }?>
											
									<? 	}else{?>
                                        <tr>
                                            
                                            <td>No record available.</td>
                                        </tr>
                                       <? }?>
                                       
                                       </tbody>
                                </table>
                                <hr />
                               
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
       
        
        
    </div>
</div>
<script>
$(document).ready(function(e) {
	 if($('#user_action').val()==''){
		 $('#user_action').val(1);
		 
	 }
	  if($('#user_action').val()==1){
		  $('.circle-plus').removeClass('opened');
		   $(this).attr("Title","Add");
	  }else{
		   $('.circle-plus').addClass('opened');
		    $(this).attr("Title","Minus");
		 }
 $('.circle-plus').on('click', function(){
	$(this).toggleClass('opened');
  if( $(this).hasClass('circle-plus closed opened')){
	  $('#user_action').val(2);
	  $(this).attr("Title","Minus");
 }else{
	  $('#user_action').val(1);
	   $(this).attr("Title","Add");
	}
})   
});

</script>
