<?php 
	global $expArr,$eduArr,$degreeArr,$yearArr,$roleArr,$engLevelArr;
	$user =  $this->user_information ;
?>
<style type="text/css">
ul#info_ul span {
	color:#e35b5a;
	font-weight:bold;
}
.widget-wrap {
	min-height:auto
}
p{
	white-space:nowrap;
}
</style>

<div class="row">
    <div class="col-sm-12">
    <div class="page-header filled full-block light">
        <div class="row">
            <div class="col-md-6">
                <h2><?=$this->pageHeading?></h2>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
        <div class="col-md-4 PaddingZero">
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Profile Image</h3>
                    </div>
                </div>
                
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="content">
                                <p class="clearfix"></p>
                                <div class="form-group text-center"> 
                                    <img src="<?php echo getUserImage($user['user_image'],'160')?>" alt="" class="img-responsive img-thumbnail"/>
                                    <ul class="list-unstyled text-center">
                                        <li><?php echo $user['user_first_name'].' '.$user['user_last_name']?></li>
                                        <li><?php echo $user['user_email']?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="col-md-8">
            <div class="widget-wrap">
                <div class="widget-header block-header margin-bottom-0 clearfix">
                    <div class="pull-left">
                        <h3>Account Information</h3>
                    </div>
                </div>
                    
                <p class="clearfix"></p>
                    
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="form-content">
                                <table class="table table-striped table-hover table-bordered Clear" style="margin:0px !important;">
                                    <tbody>
                                         <tr>
                                            <td class="" width="30%;"><b>Plan Name</b></td>
                                            <td>Status</td>
                                            <td>Action</td>
                                        </tr>
                                       <?php if(!empty($this->plan_info)){
										   foreach($this->plan_info as $pl_key=>$pl_value){?>
											 <tr>
                                            <td class="" width="30%;"><b><?php echo $pl_value['inv_pl_title']?></b></td>
                                            <td><?php $plandata= planstatus($pl_value['user_plan_isactive']);?><label class="<?php echo $plandata['labelclass']?>"><?php echo $plandata['status']?></label><?php if($pl_value['user_plan_expiredate']!='0000-00-00' && ($pl_value['user_plan_isactive']=='1' || $pl_value['user_plan_isactive']=='3')){?>&nbsp;|&nbsp;<label>Expired On : <?php echo changedateformat($pl_value['user_plan_expiredate'],"Y-m-d","d/m/Y")?></label><? }?></td>
                                            <?php if($pl_value['user_plan_isactive']=='0'){?>
												 <td><a class="btn btn-xs btn-success" href="<?php echo APPLICATION_URL.'/'.BACKEND.'/approve-plan/'.myurl_encode($pl_value['user_plan_id'])?>"  onclick="return confirm('Are you sure?')">Approve</a>&nbsp;&nbsp;<a class="btn btn-xs btn-danger" href="<?php echo APPLICATION_URL.'/'.BACKEND.'/reject-plan/'.myurl_encode($pl_value['user_plan_id'])?>"  onclick="return confirm('Are you sure?')">Reject</a></td>
											<? }else{?>
												 <td><label class="label label-warning">N/A</label></td>
											<? }?>
                                           
                                       		 </tr>
											   
											  <? }
										   ?>
										   
										  <? }else{?>
											  <tr>
                                           		 <td colspan="3">No Plan Available</td>
                                           
                                        		</tr>
											  <? }?>  
                                       
                                    </tbody>
                                </table>
                                <hr />
                               
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            
        </div>
        
       
        
        
    </div>
</div>
