<div class="page-header filled full-block light">
	<h2><i><span class="<?php echo $this->page_icon ?>"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
</div>
  <div class="widget-wrap">
    <div class="widget-container">
      <div class="widget-content">
      <div id="flash-message" class="alert alert-dismissable" style="display:none; margin:20px;"></div>
   
        <form method="post" action="<?php echo ADMIN_APPLICATION_URL?>/removeusers" onsubmit="return checkSelects()" >
          <div class="table-toolbar">
            <div class="btn-group">
              <button id="sample_editable_1_new" class="btn btn-danger"> <i class="fa fa-trash-o"></i> Delete Selected </button>
            </div>
             <div class="clearfix">&nbsp;</div>
          </div>
          <table id="sample_1" class="table table-striped table-bordered table-hover dataTable">
            <thead>
              <tr>
                <th width="5%">S.No.</th>
                <th width="5%"><input type="checkbox" class="group-checkable"  data-set="#sample_1 .checkboxes"  name="deletebcchk" id="deletebcchk" /></th>
                <th>Photo</th>
                <th>Full Name</th>
                <th>Email Address</th>
                <th>Member Since</th>
                <th>Status</th>
                <th>View</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </form>
      </div>
    </div>
  </div>

<script type="text/javascript" charset="utf-8">
var type='<?=$this->type?>';
$(document)	 .ready(function(e) {
	var sortArr=[1,3,6,7];
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": false,
		"responsive": true,
 		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/getusers" ,
		"aaSorting": [[ 0, "desc" ]],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": sortArr },
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnInitComplete": function (oSettings, json) { re_init();}
	} );
});


</script>