<?php if(true){?>
<link href="https://previews.envatousercontent.com/files/225113804/demos/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://previews.envatousercontent.com/files/225113804/demos/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

<link href="<?php echo SITE_HTTP_URL?>/public/plugins/faq/css/theme9.css" media="screen" rel="stylesheet" type="text/css">
<style>
		.jag-faq-theme9.jag-faq-bg-img .jag-flip-faq-wraper .front{
			background-image: url('images/bg1.jpg') !important;
		}
	</style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js" integrity="sha384-0s5Pv64cNZJieYFkXYOTId2HMA2Lfb6q2nAcx2n0RTLUnCAoTTsS0nKEO27XyKcY" crossorigin="anonymous"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js" integrity="sha384-ZoaMbDF+4LeFxg6WdScQ9nnR1QC2MIRxA1O9KWEXQwns1G8UNyIEZIQidzb0T1fo" crossorigin="anonymous"></script>
    <![endif]-->
<div style="background-color:#fcd116;min-height:180px;display:table;width:100%;">
    	<div style="display:table-cell;vertical-align:middle;">
        <div style="font-size:40px;text-transform:uppercase; padding-left: 68px;color: white;">
    			Frequent Questions<sub><b style="font-size:14px;text-transform:none;color:#2a2c2e;">&nbsp;part of your questions<span class="fa fa-question"></span>...</b></sub>
        </div>
        </div>
    
    </div>
<div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
<div class="clearfix">&nbsp;</div>
<div class="container">
		<div class="row">
		
		
		
		<!-- end faq theme 9 -->
	
		<div class="jag-faq-theme9 jag-faq-random-colors jag-flip-horizontal">
			<div class="col-xs-12 col-sm-6 col-md-4 jag-flip-faq-wraper"> 
				<div class="jag-flip-faq" style="perspective: 1258px; position: relative; transform-style: preserve-3d;">
				  <div class="front jag-equalheight jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: absolute; z-index: 1; height: 329px; width: 100%; transition: all 0.5s ease-out; transform: rotateX(0deg);"> 
					<span class="jag-faq-question-number" style="backface-visibility: hidden;">
						1
					</span>
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Types of layout are included in JAG FAQ Responsive HTML?
					</div>
				  </div> 
				  <div class="back jag-equalheight jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: relative; z-index: 0; height: 329px; width: 100%; transform: rotateX(-180deg); transition: all 0.5s ease-out;">
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Q. Types of layout are included in JAG FAQ Responsive HTML?
					</div>
					<div class="jag-faq-answer" style="backface-visibility: hidden;">
						<strong style="backface-visibility: hidden;">1) Accordian </strong><br style="backface-visibility: hidden;">
							Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet. Lorem ipsum dolor sitm ipsum dolor sit amet....  <br style="backface-visibility: hidden;">
							
						<!-- Trigger the modal with a button -->
						<div class="jag-faq-readmore" style="backface-visibility: hidden;">
							<a href="https://previews.envatousercontent.com/files/225113804/demos/theme9.html#" data-toggle="modal" data-target="#jag-faq-answer-1" style="backface-visibility: hidden;">Read More</a>
						</div>
					</div>
				  </div> 
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4 jag-flip-faq-wraper"> 
				<div class="jag-flip-faq" style="perspective: 1258px; position: relative; transform-style: preserve-3d;">
				  <div class="front jag-equalheight jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: absolute; z-index: 1; height: 329px; width: 100%; transition: all 0.5s ease-out; transform: rotateX(0deg);"> 
					<span class="jag-faq-question-number" style="backface-visibility: hidden;">
						2
					</span>
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Types of layout are included in JAG FAQ Responsive HTML?
					</div>
				  </div> 
				  <div class="back jag-equalheight jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: relative; z-index: 0; height: 329px; width: 100%; transform: rotateX(-180deg); transition: all 0.5s ease-out;">
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Q. Types of layout are included in JAG FAQ Responsive HTML?
					</div>
					<div class="jag-faq-answer" style="backface-visibility: hidden;">
						<strong style="backface-visibility: hidden;">1) Accordian </strong><br style="backface-visibility: hidden;">
							Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet. Lorem ipsum dolor sitm ipsum dolor sit amet....  <br style="backface-visibility: hidden;">
							
						<!-- Trigger the modal with a button -->
						<div class="jag-faq-readmore" style="backface-visibility: hidden;">
							<a href="https://previews.envatousercontent.com/files/225113804/demos/theme9.html#" data-toggle="modal" data-target="#jag-faq-answer-1" style="backface-visibility: hidden;">Read More</a>
						</div>
					</div>
				  </div> 
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4 jag-flip-faq-wraper"> 
				<div class="jag-flip-faq" style="perspective: 1258px; position: relative; transform-style: preserve-3d;">
				  <div class="front jag-equalheight jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: absolute; z-index: 1; height: 329px; width: 100%; transition: all 0.5s ease-out; transform: rotateX(0deg);"> 
					<span class="jag-faq-question-number" style="backface-visibility: hidden;">
						3
					</span>
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Types of layout are included in JAG FAQ Responsive HTML?
					</div>
				  </div> 
				  <div class="back jag-equalheight jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: relative; z-index: 0; height: 329px; width: 100%; transform: rotateX(-180deg); transition: all 0.5s ease-out;">
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Q. Types of layout are included in JAG FAQ Responsive HTML?
					</div>
					<div class="jag-faq-answer" style="backface-visibility: hidden;">
						<strong style="backface-visibility: hidden;">1) Accordian </strong><br style="backface-visibility: hidden;">
							Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet. Lorem ipsum dolor sitm ipsum dolor sit amet....  <br style="backface-visibility: hidden;">
							
						<!-- Trigger the modal with a button -->
						<div class="jag-faq-readmore" style="backface-visibility: hidden;">
							<a href="https://previews.envatousercontent.com/files/225113804/demos/theme9.html#" data-toggle="modal" data-target="#jag-faq-answer-1" style="backface-visibility: hidden;">Read More</a>
						</div>
					</div>
				  </div> 
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4 jag-flip-faq-wraper"> 
				<div class="jag-flip-faq" style="perspective: 1200px; position: relative; transform-style: preserve-3d;">
				  <div class="front jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: absolute; z-index: 1; height: 300px; width: 100%; transition: all 0.5s ease-out; transform: rotateX(0deg);"> 
					<span class="jag-faq-question-number" style="backface-visibility: hidden;">
						4
					</span>
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						How to integrate JAG FAQ visual composer addon ?
					</div>
				  </div> 
				  <div class="back jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: relative; z-index: 0; height: 300px; width: 100%; transform: rotateX(-180deg); transition: all 0.5s ease-out;">
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Q. How to integrate JAG FAQ visual composer addon ?
					</div>
					<div class="jag-faq-answer" style="backface-visibility: hidden;">
						To configure JAG FAQ Visual composer addon: <br style="backface-visibility: hidden;">
						You can implement following steps: <br style="backface-visibility: hidden;">
						1) Open Dashboard <br style="backface-visibility: hidden;">
						<!-- Trigger the modal with a button -->
						<div class="jag-faq-readmore" style="backface-visibility: hidden;">
							<a href="https://previews.envatousercontent.com/files/225113804/demos/theme9.html#" data-toggle="modal" data-target="#jag-faq-answer-1" style="backface-visibility: hidden;">Read More</a>
						</div>
					</div>
				  </div> 
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4 jag-flip-faq-wraper"> 
				<div class="jag-flip-faq" style="perspective: 1200px; position: relative; transform-style: preserve-3d;">
				  <div class="front jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: absolute; z-index: 1; height: 300px; width: 100%; transition: all 0.5s ease-out; transform: rotateX(0deg);"> 
					<span class="jag-faq-question-number" style="backface-visibility: hidden;">
						5
					</span>
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						How to integrate JAG FAQ visual composer addon ?
					</div>
				  </div> 
				  <div class="back jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: relative; z-index: 0; height: 300px; width: 100%; transform: rotateX(-180deg); transition: all 0.5s ease-out;">
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Q. How to integrate JAG FAQ visual composer addon ?
					</div>
					<div class="jag-faq-answer" style="backface-visibility: hidden;">
						To configure JAG FAQ Visual composer addon: <br style="backface-visibility: hidden;">
						You can implement following steps: <br style="backface-visibility: hidden;">
						1) Open Dashboard <br style="backface-visibility: hidden;">
						<!-- Trigger the modal with a button -->
						<div class="jag-faq-readmore" style="backface-visibility: hidden;">
							<a href="https://previews.envatousercontent.com/files/225113804/demos/theme9.html#" data-toggle="modal" data-target="#jag-faq-answer-1" style="backface-visibility: hidden;">Read More</a>
						</div>
					</div>
				  </div> 
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-4 jag-flip-faq-wraper"> 
				<div class="jag-flip-faq" style="perspective: 1200px; position: relative; transform-style: preserve-3d;">
				  <div class="front jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: absolute; z-index: 1; height: 300px; width: 100%; transition: all 0.5s ease-out; transform: rotateX(0deg);"> 
					<span class="jag-faq-question-number" style="backface-visibility: hidden;">
						6
					</span>
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						How to integrate JAG FAQ visual composer addon ?
					</div>
				  </div> 
				  <div class="back jag-equalheight" style="backface-visibility: hidden; transform-style: preserve-3d; position: relative; z-index: 0; height: 300px; width: 100%; transform: rotateX(-180deg); transition: all 0.5s ease-out;">
					<div class="jag-faq-question" style="backface-visibility: hidden;">
						Q. How to integrate JAG FAQ visual composer addon ?
					</div>
					<div class="jag-faq-answer" style="backface-visibility: hidden;">
						To configure JAG FAQ Visual composer addon: <br style="backface-visibility: hidden;">
						You can implement following steps: <br style="backface-visibility: hidden;">
						1) Open Dashboard <br style="backface-visibility: hidden;">
						<!-- Trigger the modal with a button -->
						<div class="jag-faq-readmore" style="backface-visibility: hidden;">
							<a href="https://previews.envatousercontent.com/files/225113804/demos/theme9.html#" data-toggle="modal" data-target="#jag-faq-answer-1" style="backface-visibility: hidden;">Read More</a>
						</div>
					</div>
				  </div> 
				</div>
			</div>
		</div>
		<!-- end faq theme 9 -->
	</div>
	</div>
	<!-- Modal -->
	<div id="jag-faq-answer-1" class="modal fade" role="dialog" tabindex="-1">
	  <div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h4 class="modal-title">Q. What type of layouts are included in JAG FAQ Responsive HTML?</h4>
		  </div>
		  <div class="modal-body">
				<strong>Types of layout:</strong> <br>
				<strong>1) Accordian </strong><br>
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.  <br><br>
				
				<strong> 2) Flip with grid </strong><br>
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. <br><br>
				
				<strong>3) Simple Listing </strong><br>
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. 
				Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.  <br><br>
			
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  </div>
		</div>
	  </div>
	</div>
	<!-- End Modal -->

<div class="container-fluid padding0" style="clear:both; margin-bottom:41px;">
	<div class="container padding0 faq_margn">
    	<div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">What is Lorem Ipsum?</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        
        <div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">What is Lorem Ipsum?</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        <div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">What is Lorem Ipsum?</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        
    </div>
</div>

<script type="text/javascript" src="https://previews.envatousercontent.com/files/225113804/demos/vendor/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo SITE_HTTP_URL?>/public/plugins/faq/js/flip.js"></script>
<script type="text/javascript" src="<?php echo SITE_HTTP_URL?>/public/plugins/faq/js/jquery.matchHeight.js"></script>
<script type="text/javascript" src="<?php echo SITE_HTTP_URL?>/public/plugins/faq/js/jag-faq-custom.js"></script>
<? }?>