			<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Q. <?php echo $faqData["faq_question"]?></h4>
		  </div>
		  <div class="modal-body">
				<?php echo nl2br($faqData["faq_answer"]);?>
			
		  </div>
          
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  </div>
<?php exit();?>