
<?php if(false){?>
<style>

</style>
<?php if(true){?>
<div class="staticheadBlock">
    				<div class="staticchildBlock">
                    	<div class="container">
                        	<div class="row">
        							<div class="staticTextBlock">
    						Services<sub><b class="staticsubTextBlock">&nbsp;we provide best you...</b></sub>
       					 </div>	
                         	</div>
       				 	</div>
                     </div>
    
   				 </div>
                 <div class="contentBlock securityBox">
<div class="container">
<div class="makediv" style="margin-top:130px;margin-bottom:80px;">
<div class="col-sm-3">
<div style="font-size:100px;border-radius:50%;width:150px;height:150px;background-color:#fcd116;margin:0 auto;text-align:center;" >
	
    <span class="fa fa-tasks" style="display: flex;justify-content: center; align-items: center; width: 100%;height: 100%;"></span>
    
</div>
<h1 class="text-center" >Planning</h1>
<div style="font-size:14px; color:#333;padding:0 0 10px 0;" class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </div>
</div>
<div class="col-sm-3">
<div style="font-size:100px;border-radius:50%;width:150px;height:150px;background-color:#fcd116;margin:0 auto;text-align:center;" ><span class="fa fa-cogs" style="display: flex;justify-content: center; align-items: center; width: 100%;height: 100%;"></span></div>
<h1 class="text-center" >Process</h1>
<div style="font-size:14px; color:#333;padding:0 0 10px 0;" class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </div>
</div>
<div class="col-sm-3">
<div style="font-size:100px;border-radius:50%;width:150px;height:150px;background-color:#fcd116;margin:0 auto;text-align:center;" ><span class="fa fa-user" style="display: flex;justify-content: center; align-items: center; width: 100%;height: 100%;"></span></div>
<h1 class="text-center" >Experts</h1>
<div style="font-size:14px; color:#333;padding:0 0 10px 0;" class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </div>
</div>
<div class="col-sm-3">
<div style="font-size:100px;border-radius:50%;width:150px;height:150px;background-color:#fcd116;margin:0 auto;text-align:center;" ><span class="fa fa-star" style="display: flex;justify-content: center; align-items: center; width: 100%;height: 100%;"></span></div>
<h1 class="text-center" >Trusts</h1>
<div style="font-size:14px; color:#333;padding:0 0 10px 0;" class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </div>
</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="col-sm-8 col-md-6" style="margin: 0 auto;float: none;">
<div class="strate_box_top_panel">
<div class="strate_box_top_head">our way –</div>

<div class="strate_box_top_sub_head">Strategies of Work</div>

<div class="strate_box_top_sub_text">Economic services provided by the finance industry, which encompasses a broad range of businesses that manage money, including credit unions.</div>
</div>
</div>
</div>
<div class="bottom_border"></div>

<div class="makediv" style="margin-top:30px;margin-bottom:30px;">
		<div><a class="support_about" style="margin:0 auto;">Sign Up</a></div>
</div>


<div class="bottom_border"></div>

<div style="margin-top:40px;">
<h1 class="text-center">Our Process</h1>
</div>

<div class="overview_intro">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</div>
</div>

<div class="makediv overview_box">
<div class="strate_box_top">
<div class="strate_box_top_inner">
<div class="strate_box_top_panel" style="background: rgba(252, 209, 22, 0.57);">
<div class="text-center" style="margin-bottom:30px;"><img src="{img_url}/regal.png" /></div>
<div class="strate_box_top_head">our main goal –</div>

<div class="strate_box_top_sub_head">Protect your work</div>

<div class="strate_box_top_sub_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</div>
</div>
</div>
</div>
</div>




</div>

<div class="staticheadBlock">
    				<div class="staticchildBlock">
                    	<div class="container">
                        	<div class="row text-center">
        							<div class="staticTextBlock">
    						SERVICES<sub><b class="staticsubTextBlock">&nbsp;It is a long established fact that a reader will be distracted....</b></sub>
       					 </div>	
                         	</div>
       				 	</div>
                     </div>
    
   				 </div>
               
<?php if(true){?>
	<div class="staticheadBlock">
    				<div class="staticchildBlock">
                    	<div class="container">
                        	<div class="row">
        							<div class="staticTextBlock">
    						Blessings<sub><b class="staticsubTextBlock">&nbsp;It is a long established fact that a reader will be distracted....</b></sub>
       					 </div>	
                         	</div>
       				 	</div>
                     </div>
    
   				 </div>
                 <div style="margin-top:40px;margin-bottom:40px;">
						<h1 class="text-center">Blessings</h1>
				
                <div class="overview_intro">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</div>
                
                <div class="overview_intro">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</div>
                
                <div class="overview_intro">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</div>
                 <div class="bottom_border"></div>
                </div>
               
<? }?>


<? }?>

<? }?>
<?php
if(true){

if($this->page_content['page_id']==14 && !isset($_COOKIE["password_isvalid"])){
?>
<div style="min-height:500px;">
<h1 class="text-center" style="color:#283742;padding:5px;font-size:30px;">Password Required</h1>
<div class="text-center" style="max-width:600px;margin:0 auto;padding:15px;">
			<form action="" method="post" class="profile_form">
            <div class="makediv">
				<div class="form-group text-left">
                <input type="password" name="pw" id="pw" class="form-control required" placeholder="Password"><br>
                </div>
                <input type="submit" value="Submit Password" class="btn SiteButton">
             </div>  
                <p>
                <br><span class="pw">Please input and submit the required password to access this page.</span>
                </p>
                
              </form>
</div>

</div>
<?
}
else{
?>

				
                
                
            	<?php echo $this->page_content['page_content']; ?>
                
                
                
         
<?
}

}
?>
