<?php if(false){?>
<style>
.blue {
    background-color: #283742;
}
.section-dark {
    color: #fff;
}
@media (min-width: 768px)
{
.section {
    padding: 88px 0 94px;
}
.quotation {
    text-align: center;
}
.site-width {
    box-sizing: content-box;
    max-width: 984px;
    margin: 0 auto;
}
blockquote {
    font-size: 34px;
    line-height: 48px;
	border-left: 5px solid #fcd116;
}

blockquote+cite {
    display: block;
    margin: 30px 0 0;
}
strong, b {
    font-weight: 500;
}
.font-medium {
    font-size: 16px;
    font-weight: 300;
      line-height: 24px;
}
}
.marg-lg-b140 {
    margin-bottom: 140px;
}
.no-padd {
    padding-left: 0px;
    padding-right: 0px;
}
.rome-about-us-wrapper {
    position: relative;
    min-height: 480px;
}
.rome-about-us-images {
    text-align: center;
}
.rome-about-us-images img:first-child {
    margin-bottom: 27px;
}
.rome-about-us-images img {
    margin: 0 auto;
}
@media (min-width: 992px)
{
.rome-about-us {
    position: absolute;
    top: 50%;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    margin-top: 0;
    right: 0;
}
}
.rome-about-us {
   /* margin-top: 40px;*/
    text-align: center;
}
.t-center {
    text-align: center;
}
.rome-heading .rome-subtitle {
    font-size: 13px;
    line-height: 2;
    letter-spacing: 3.9px;
    text-transform: uppercase;
}
.rome-heading-yellow .rome-subtitle {
    color: #444;
}
.rome-heading h2, .rome-baner-container .rome-heading h1, .rome-swiper-content .rome-heading h1 {
    font-weight: 800;
    font-size: 32px;
    line-height: 1.125;
    letter-spacing: 1.6px;
    text-transform: uppercase;
    position: relative;
    margin: 14px 0 26px;
    display: inline-block;
}
.rome-heading .rome-heading-content {
    font-size: 14px;
    line-height: 1.71429;
    letter-spacing: 0.7px;
    font-style: italic;
    margin-bottom: 0;
}
.rome-heading .rome-heading-content {
    font-size: 14px;
    line-height: 1.71429;
    letter-spacing: 0.7px;
    font-style: italic;
    margin-bottom: 0;
}
.rome-about-us .rome-btn-donate {
    margin-top: 32px;
}
</style>
<div class="staticheadBlock">
    				<div class="staticchildBlock">
                    	<div class="container">
                        	<div class="row">
        							<div class="staticTextBlock">
    										Our Mission<sub><b class="staticsubTextBlock">&nbsp;target we achieve...</b></sub>
       							 </div>	
                         	</div>
       				 	</div>
                     </div>
    
   				 </div>

<div class="container marg-md-b140 marg-lg-b140 marg-sm-b100 marg-xs-b70 no-padd">
<div class="row">
<div class="rome-about-us-wrapper clearfix">
<div class="col-md-6 col-sm-12 rome-about-us-images">
<img src="<?php echo HTTP_IMG_PATH?>/commitment.png" alt="" class="img-responsive" height="270px" style="height:270px;">
<img src="<?php echo HTTP_IMG_PATH?>/commitment.png" alt="" class="img-responsive" height="270px"  style="height:270px;">
</div>
<div class="col-md-5 col-md-offset-1 col-sm-12 rome-about-us no-padd">
<section class="rome-heading rome-heading-yellow t-center">
<div class="rome-subtitle">
<p>Mission</p>
</div>
<h2><span>Why we ?</span></h2>
<div class="rome-heading-content grey-text">
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s </p>
</div>
</section>
<div class="rome-about-us-text">
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500sLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500sLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
</div>
<div class="clearfix service_text_boxAbout" >
            		<a class="support_about" style="margin:0 auto;">More About us</a>
          		  </div>
        			<div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
</div>
</div>
</div>

<div class="row">
<div class="rome-about-us-wrapper clearfix">

<div class="col-md-5 col-md-offset-1 col-sm-12 rome-about-us no-padd" style="right:auto;">
<section class="rome-heading rome-heading-yellow t-center">
<div class="rome-subtitle">
<p>Mission</p>
</div>
<h2><span>Why we ?</span></h2>
<div class="rome-heading-content grey-text">
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s </p>
</div>
</section>
<div class="rome-about-us-text">
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500sLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500sLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
</div>
<div class="clearfix service_text_boxAbout" >
            		<a class="support_about" style="margin:0 auto;">More About us</a>
          		  </div>
        			<div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
</div>
<div class="col-md-6 col-sm-12 rome-about-us-images" style="float:right;">
<img src="<?php echo HTTP_IMG_PATH?>/commitment.png" alt="" class="img-responsive" height="270px" style="height:270px;">
<img src="<?php echo HTTP_IMG_PATH?>/commitment.png" alt="" class="img-responsive" height="270px"  style="height:270px;">
</div>
</div>
</div>
</div>
<div class="text-center"><img src="<?php echo HTTP_IMG_PATH?>/regal_y.png" /></div>
<div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-bottom: 30px;"></div>
						<div><h1 class="text-center">Why do we use it?</h1></div>
						
                        <div style="max-width:700px;margin:0 auto;color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;margin-bottom:140px;">
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
					</div>


<div class="staticheadBlock">
    				<div class="staticchildBlock">
                    	<div class="container">
                        	<div class="row">
        							<div class="staticTextBlock">
    						Overview<sub><b class="staticsubTextBlock">&nbsp;about our way...</b></sub>
       					 </div>	
                         	</div>
       				 	</div>
                     </div>
    
   				 </div>

<div class="contentBlock">

		<div class="container">
        		<div><h1 class="text-center">Hey everyone!</h1></div>
        		<div style="max-width:700px;margin:0 auto;color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
                <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
						<div><h1 class="text-center">Why do we use it?</h1></div>
						
                        <div style="max-width:700px;margin:0 auto;color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
					</div>

        
        </div>
        
        <div class="makediv overview_box">
	<div class="strate_box_top">
    <div class="strate_box_top_inner">
           <div class="strate_box_top_panel" style="margin: 0 auto;
    background: rgba(252, 209, 22, 0.57);
    padding: 40px;
    color: #283742;
    max-width: 600px;">
            <div class="strate_box_top_head" style="color:#283742;text-align:center;">our main goal –</div>
            <div class="strate_box_top_sub_head" style="color:#283742;text-align:center;">Strategies That Work</div>
            <div class="strate_box_top_sub_text" style="color:#283742;max-width:none;text-align:center;">
                Economic services provided by the finance industry, which encompasses a broad range of businesses that manage money, including credit unions.
            </div>
            
            </div>
    </div>
    </div>
</div>
        <div class="container">
        		<div><h1 class="text-center">Our Flow!</h1></div>
        		<div style="max-width:700px;margin:0 auto;color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
                <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
						<div><h1 class="text-center">Why do we use it?</h1></div>
						
                        <div style="max-width:700px;margin:0 auto;color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
					</div>
                    <div class="clearfix">&nbsp;</div>
                    <div class="clearfix">&nbsp;</div>
				<div class="clearfix service_text_boxAbout" >
            		<a class="support_about" style="margin:0 auto;">More About us</a>
          		  </div>
        			<div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        <section class="section section-dark section-quote blue quotation" id="quotation" style="margin-top: 30px;">
        <div class="site-width">
          <blockquote>
            “Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.”
          </blockquote><cite class="font-medium"><strong>Celbs White</strong>, Founder</cite>
        </div>
      </section>
</div>
<? }?>
<?php
if(true){
if($this->page_content['page_id']==3){
?>
<div class="staticpage" id="aboutus">
	<div class="staticpage-bg">
        <div class="container text-center">
            <h2 class="staticpage-header">About Us</h2>
        </div>
    </div>
    <?php echo $this->page_content['page_content']; ?>
    
    <!-- Contact Box -->
	<div class="home-registration-block">
        <div class="registration-block" style="background-image:url(<?php echo HTTP_IMG_PATH?>/5.jpg);background-size:cover;background-position:center top;width:100%;background-attachment:fixed;padding-top: 6.5%;">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="content-icon-wrape">
                        	<div class="circled-icon"><i class="fa fa-map-marker"></i></div>
                        	<div class="circled-desc"><?php echo $this->site_config['site_address'] ?></div>
                        </div>
                    </div>
                
                    <div class="col-md-4">
                        <div class="content-icon-wrape">
                        	<div class="circled-icon"><i class="fa fa-mobile"></i></div>
                        	<div class="circled-desc"><?php echo $this->site_config['site_phone'] ?></div>
                        </div>
                    </div>
                
                    <div class="col-md-4">
                        <div class="content-icon-wrape">
                        	<div class="circled-icon"><i class="fa fa-envelope"></i></div>
                        	<div class="circled-desc"><?php echo $this->site_config['contact_mail_address'] ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix" style="height:0;clear:both">&nbsp;</div>    
</div>
<?
}
else if($this->page_content['page_id']==9){
?>
<div class="staticpage" id="ourservices">
	<div class="staticpage-bg">
        <div class="container text-center">
            <h2 class="staticpage-header">Our Services</h2>
        </div>
    </div>
    <?php echo $this->page_content['page_content']; ?>
</div>
<?
}
else{
?>

				<?php 
                if($this->page_content['page_id']==7 || $this->page_content['page_id']==8){
                ?>
               
                <div class="staticheadBlock">
    				<div class="staticchildBlock">
        				<div class="staticTextBlock">
    						Terms & Policies<sub><b class="staticsubTextBlock">&nbsp;Last Updated On: &nbsp; <?php echo date("d F, Y ",strtotime($this->page_content['page_updated'])) ?>...</b></sub>
       					 </div>
       				 </div>
    
   				 </div>
                
                <?
                }
                else{
                ?>
                
                <?
                }
                ?>
                <div class="container-fluid padding0" style="clear:both; margin-bottom:41px;">
						<div class="container padding0 faq_margn">
    	<div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">Objective and Scope of Policy?</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        
        <div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">Our Policy?</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        <div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">Collection of Information</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
        <div class="faq_wrapper" style="margin-bottom:30px;">
        	<div class="col-md-12 faq_ques">
            
            	<h3 style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:bold;margin-bottom:0;">Our Commitment</h3>
            </div>
            <div class="col-md-12 faq_ans" style="color:#283742;line-height: 1.8;font-size: 16px;font-weight:300;">
            	<p style="margin:0;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. printer took a galley of type and scrambled it to make a type specimen book.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', .</p>
            </div>
            <div style="width:30%;border: solid 1px #fcd116;margin:0 auto;margin-top: 30px;"></div>
        </div>
    </div>
				</div>
                
            	<?php /*?><?php echo $this->page_content['page_content']; ?><?php */?>
                
                <?php 
				if($this->page_content['page_id']==3){
				?>
				<div id="addressfooter">
                    <div class=" bg-white footer-top">
                        <div class="container">
                            <div class="row margin-four">
                                 phone 
                                <?php 
								if(!empty($this->site_config['site_phone'])){
								?>
								<div class="col-md-4 col-sm-4 text-center animateblock">
                                	<i class="fa fa-phone fa-3x black-text"></i>
                                	<h6 class="about-detail-text"><?php echo $this->site_config['site_phone']?></h6>
                                </div>
                                 end phone 
								<?
								}
								
								if(!empty($this->site_config['site_address'])){
								?>
								 address 
                                <div class="col-md-4 col-sm-4 text-center animateblock">
                                    <i class="fa fa-map-marker fa-3x small-icon black-text"></i>
                                    <h6 class="about-detail-text"><?php echo $this->site_config['site_address']?></h6>
                                </div>
                                 end address 
								<?	
								}
								
                                
                                if(!empty($this->site_config['contact_mail_address'])){
								?>
                                 email 
                                <div class="col-md-4 col-sm-4 text-center animateblock">
                                <i class="fa fa-envelope-o fa-3x small-icon black-text"></i>
                                    <h6 class="about-detail-text">
                                    <a href="mailto:<?php echo $this->site_config['contact_mail_address']?>" class="black-text"><?php echo $this->site_config['contact_mail_address']?></a></h6>
                                </div>
                                 end email 
                                <?
								}
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
				<?	
				}
				?>
                
         
<?
}

}
?>
