<style>

/*.regal_pricing_box1_wrapper .title{font-size: 16px;font-weight: bold;}
.regal_pricing_box1_wrapper .desc{color: #283742;line-height: 1.8;font-size: 14px;margin-bottom: 15px;}



.regal_pricing_box2_wrapper .plan_title{background: #252525;color: #fff;text-align: center;padding: 25px;font-size: 18px;border-top-left-radius: 5px;border-top-right-radius: 5px;}
.regal_pricing_box2_wrapper .plan_desc_wrapper{
    border: 1px solid #CCC;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
}
.plan_desc_wrapper .best_for{padding: 15px 8px;font-size: 13px;background: #f9f9f9;}
.plan_desc_wrapper .best_for span:first-child{color:#252525; font-weight:bold;}
.plan_desc_wrapper .plan_small_desc{ padding:15px 8px;}
.plan_get_started a{ display:inline-block; width:100%; color:#fff; text-decoration:none; background:#252525; padding:15px 8px; text-align:center; border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;}
.plan_get_started a:hover{ background:rgba(252,209,22,1);}
.regal_pricing_box2_wrapper:hover{box-shadow: 0 0 4px 1px #252525;}

.plan_small_desc .list-icons{ margin:0; padding:0;}
.plan_small_desc .list-icons li {font-size: 13px;line-height: 28px; list-style:none;color: #35444e; font-weight:bold;}
ul.list-icons li i {font-size: 12px;}
.plan_small_desc .list-icons li span{ display:inline-block; vertical-align:top;}
.plan_small_desc .list-icons li .icon_wrapper{width: 10%; text-align:center; color:#fcd116}
.plan_small_desc .list-icons li .icon_desc_wrapper{width: 88%;}
.plan_small_desc hr{ margin-top:10px; margin-bottom:10px;}*/


</style>
<div class="staticpage staticpage_pricing_wrapper" >
 
	<?php echo $this->page_content['page_content']?>
    	
        <?php if(false){?>
        
	<div class="hide pricing-content-wrapper">
    
        <div class="container">
        
           <?php /*?> <div class="row">
            	
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box1_wrapper">
                        <div class="title">
                            No additional trading fees.
                        </div>
                        <div class="desc">
                        	We don't charge you additional transaction fees to buy and sell securities.
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box1_wrapper">
                        <div class="title">
                            No additional trading fees.
                        </div>
                        <div class="desc">
                        	There are no additional fees for depositing or withdrawing from your account.
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box1_wrapper">
                        <div class="title">
                           Unlimited rebalancing.
                        </div>
                        <div class="desc">
                        	We rebalance your portfolio efficiently and automatically – at no additional cost to you.
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box1_wrapper">
                        <div class="title">
                            Satisfaction guaranteed.
                        </div>
                        <div class="desc">
                        	We're committed to providing our customers with a great investing experience.
                        </div>
                    </div>
                </div>
                
            </div><!--End Pricing Page Row-1 --><?php */?>
            
            <?php /*?><div class="row">
            	
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box2_wrapper">
                        <div class="plan_title">
                           The Come Up
                        </div>
                        <div class="plan_desc_wrapper">
                        	<div class="best_for">
                            	<span>Best For : </span><span>individual users monitoring their investment</span>
                            </div>
                        	<div class="plan_small_desc">
                            	<ul class="list-icons">
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Advanced tax-saving strategies</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Everything in one place</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Access to licensed financial experts anytime, anywhere</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                      </li>
                                 </ul>
                            </div>
                            <div class="plan_get_started">
                            	<a href="">Get Started</a>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box2_wrapper">
                        <div class="plan_title">
                            Hole In 1
                        </div>
                        <div class="plan_desc_wrapper">
                        	<div class="best_for">
                            	<span>Best For : </span><span>individual users monitoring their investment</span>
                            </div>
                        	<div class="plan_small_desc">
                            	<ul class="list-icons">
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Advanced tax-saving strategies</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Everything in one place</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Access to licensed financial experts anytime, anywhere</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                      </li>
                                 </ul>
                            </div>
                            <div class="plan_get_started">
                            	<a href="">Get Started</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box2_wrapper">
                        <div class="plan_title">
                            Direct Investing
                        </div>
                        <div class="plan_desc_wrapper">
                        	<div class="best_for">
                            	<span>Best For : </span><span>individual users monitoring their investment</span>
                            </div>
                        	<div class="plan_small_desc">
                            	<ul class="list-icons">
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Advanced tax-saving strategies</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Everything in one place</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Access to licensed financial experts anytime, anywhere</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                      </li>
                                 </ul>
                            </div>
                            <div class="plan_get_started">
                            	<a href="">Get Started</a>
                            </div>
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                	<div class="regal_pricing_box2_wrapper">
                        <div class="plan_title">
                            Five Finger Discount
                        </div>
                        <div class="plan_desc_wrapper">
                        	<div class="best_for">
                            	<span>Best For : </span><span>individual users monitoring their investment</span>
                            </div>
                        	<div class="plan_small_desc">
                            	<ul class="list-icons">
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Advanced tax-saving strategies</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Everything in one place</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Access to licensed financial experts anytime, anywhere</span>
                                          <hr />
                                      </li>
                                      <li>
                                          <span class="icon_wrapper"><i class="fa fa-check orange_text"></i></span> 
                                          <span class="icon_desc_wrapper">Reliable customer service </span>
                                      </li>
                                 </ul>
                            </div>
                            <div class="plan_get_started">
                            	<a href="">Get Started</a>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div><!--End Pricing Page Row-2 --><?php */?>
            <div class="row">
            	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                	<div class="regal_pricing_head_content">
                    	Globally transition alternative networks vis-a-vis user friendly architectures. Rapidiously productivate standards compliant services vis-a-vis holistic technology. Objectively underwhelm impactful action items through clicks-and-mortar "outside the box" thinking. Proactively grow viral e-services before intuitive infrastructures. Phosfluorescently whiteboard premium initiatives after integrated e-markets.

Phosfluorescently embrace maintainable initiatives for backward-compatible markets. Synergistically scale resource maximizing solutions and collaborative methods of empowerment. Compellingly iterate team driven information before user-centric markets. Intrinsicly productivate progressive information rather than orthogonal quality vectors. Monotonectally engage prospective imperatives with extensive e-tailers.

Synergistically disseminate multidisciplinary imperatives with highly efficient niches. Globally foster wireless platforms whereas superior convergence. Seamlessly synthesize leveraged potentialities for synergistic content. Dramatically syndicate enterprise-wide alignments before installed base technology.
                    </div>
                </div>
            </div>
            <div class="regal_box3_wrapper">
            	<div class="regal_box3_left_panel regal_box3_left_right_panel">
                	<img src="<?=HTTP_IMG_PATH.'/advisor_benke.jpg'?>" class="img-responsive" />
                </div>
                <div class="regal_box3_right_panel regal_box3_left_right_panel">
                	<div class="regal_box3_right_content_wrappe">
                    	<div class="regal_pricing_box3_title">REGAL INVESTMENTS ADVISOR NETWORK&trade;</div>
						<div class="regal_pricing_box3_bold_content">Looking for a dedicated one-on-one relationship with a financial advisor?</div>
<div>Get matched with a pre-vetted CFP® professional who can provide comprehensive financial planning. Advisors may have minimum balance requirements, which typically begin at $100,000.</div>
                    </div>
                </div>
            </div>
       			
            
     
            
        </div><!--End Pricing Page Container-->
        
        <div class="makediv overview_box">
            <div class="strate_box_top">
            <div class="strate_box_top_inner">
            <div class="strate_box_top_panel" style="background: rgba(252, 209, 22, 0.57);">
            <?php /*?><div class="text-center" style="margin-bottom:30px;"><img src="{img_url}/regal.png" /></div><?php */?>
             <div class="text-center" style="margin-bottom:30px;"><img src="<?=HTTP_IMG_PATH?>/regal.png" /></div>
            
            <div class="strate_box_top_head">our main goal &ndash;</div>
            
            <div class="strate_box_top_sub_head">Protect your work</div>
            
            <div class="strate_box_top_sub_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</div>
            </div>
            </div>
            </div>
            </div>
        
        <div class="container">
        	<div class="regal_box3_wrapper regal_box4_wrapper ">
            
                <div class="regal_box3_right_panel regal_box3_left_right_panel">
                	<div class="regal_box3_right_content_wrappe">
                    	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </div>
                </div>
                
                <div class="regal_box3_left_panel regal_box3_left_right_panel">
                	<img src="<?=HTTP_IMG_PATH.'/pricing.jpg'?>" class="img-responsive" />
                </div>
            </div>
        </div>
    </div><!--End Pricing Wrapper-->
<? }?>
</div><!-- End Pricing Page-->