<?php /*?><?php if(isset($this->layout_show_map) and $this->layout_show_map){?><?php */?>

        <div id="googleMap" style="width:100%;height:666px;"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=<?php echo GOOGLE_MAP_API_KEY?>"></script>
   
<script type="text/javascript">
var map;

var sch_latitude='<?=$this->SITE_CONFIG['site_latitude']?>';
var sch_longitude='<?=$this->SITE_CONFIG['site_longitude']?>';

var myCenter=new google.maps.LatLng(sch_latitude,sch_longitude);

	function initialize()
	{
		var mapProp = {
			  center:myCenter,
			  zoom:11,
  			  mapTypeId:google.maps.MapTypeId.ROADMAP,
  			  scrollwheel: false,
  			  styles: {
     				 saturation:1
  				}
  			};   
  
		var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

		var positionLoc =new google.maps.LatLng(sch_latitude,sch_longitude);
		var position=new google.maps.Marker({
 				 position:positionLoc,
  				icon:'public/img/regal_y.png'
			});

			position.setMap(map);
		}
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<?php /*?><?php  } ?><?php */?>