<footer class="footer-container">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="footer-left">
                	<span>© <?php echo date('Y')?> <a href="<?php echo $this->url('dashboard')?>"><?=$this->SITE_CONFIG['site_name']?></a></span>
                </div>
            </div>
        </div>
    </div>
</footer>