<?php
//echo 
$form->setAttribute('action', $this->url('adminpassword', array('action' => 'changepassword')));
$form->setAttribute('class','profile_form2 j-forms');
$form->prepare();
echo $this->form()->openTag($form); 
$image = getUserImage($adminData['user_image'],"300");
?>

<div class="page-header filled full-block light">
    <div class="row">
        <div class="col-md-12 col-sm-12">
           
             <h2><i><span class="zmdi zmdi-key"></span>&nbsp;Change Password</i></h2>
            
        </div>
        <div class="col-md-6 col-sm-6">
           <?php /*?> <ul class="list-page-breadcrumb">
                <li><a href="<?php echo $this->url('dashboard')?>">Home <i class="zmdi zmdi-chevron-right"></i></a></li>
                <li class="active-page"> Update profile</li>
            </ul><?php */?>
        </div>
    </div>
</div>

<div class="content-div">
    <div class="row">
    	<div class="col-md-4">
            <div class="widget-wrap">
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="content">
                                <div class="form-group text-center">
                                	<img src="<?php echo $image?>" alt="" class="img-responsive img-thumbnail" style="max-height:300px"/>
                                    <ul class="list-unstyled text-center">
                                        <li><?php echo $adminData['user_first_name'].' '.$adminData['user_last_name']?></li>
                                        <li><?php echo $adminData['user_email']?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-md-8">
            <div class="widget-wrap">
                <div class="widget-container">
                    <div class="widget-content">
                        <div class="row">
                            <div class="form-content" style="padding:10px"> 
                                <div class="row">
                                    <div class="col-md-12 unit form-group">
                                        <label class="label">
                                        	<?=$this->formLabel($form->get('user_old_password'))?>
                                        </label>
                                        <div class="input">
                                        	<label class="icon-left" for="text"> <i class="fa fa-key"></i> </label>
                                        	<?= $this->formElement($form->get('user_old_password'))?>
                                        </div>
                                    </div>
                                    <div class="col-md-12 unit form-group">
                                        <label class="label">
                                        	<?=$this->formLabel($form->get('user_password'))?>
                                        </label>
                                        <div class="input">
                                        	<label class="icon-left" for="email"> <i class="fa fa-key"></i> </label>
                                        	<?=$this->formElement($form->get('user_password'))?>
                                        </div>
                                    </div>
                                    <div class="col-md-12 unit form-group">
                                        <label class="label">
                                        	<?=$this->formLabel($form->get('user_rpassword'))?>
                                        </label>
                                        <div class="input">
                                        	<label class="icon-left" for="email"> <i class="fa fa-key"></i> </label>
                                        	<?=$this->formElement($form->get('user_rpassword'))?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-footer text-center">
                            	<button type="submit" class="btn site-btn SiteButton">Update Password</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>