
<div id="grad" class="animated fadeIn element_block">
<div class="makediv relative">
<?php echo $this->render("auth-acl/profile/_profile_side_bar.phtml"); ?>


	<div class="main-content container confirmdepositDiv " >

		<div class="menu">
        		<?php echo $this->getPageData["page_content"];?>
		</div>
    </div>
    	<div class="text-center">
        	<button type="button" name="contBtn" class="btn SiteButton upload-result" id="contBtn" onclick="window.location='<?php echo SITE_HTTP_URL?>/dashboard'"><span>Continue</span></button>
        </div>
        <div class="clearfix">&nbsp;</div>
         <div class="clearfix">&nbsp;</div>
    </div>
   </div>

