<style>
body,html{height:100%;}
</style>
<div style="display: table;width: 100%;height: 100%; background-image: url('<?php echo HTTP_IMG_PATH ?>/error.jpg');background-repeat: no-repeat;background-size: cover;">


<div style="display: table-cell;
    vertical-align: middle;">
	<div class="text-center" style="margin-top:-8%;">
    			
    			<h1 style="font-size:70px;">404</h1>
    			<h3 style="margin-bottom:10px;">Page Not Found</h3>
            	<h4 >Whoops, You're lost.</h4>
			</div>
</div>
</div>
<?php /*?><div style="max-width:400px;padding:20px;margin-top:140px;" class="center-block">
  <h1 class="center" style="margin-top:60px;">404 Page Not Found</h1>
 <div class="center row-fluid index_main_div" style="min-height:200px;" >
  <div class="span12">
    <div class="row-fluid page-404" style="margin-top:50px;margin-bottom:50px;">
      <div class="span5 number">  </div>
      <div class="span7 details">
        <h2>Opps, You're lost.</h2>
        <p> We can not find the page you're looking for.</p>
        <a href="<a href="<?=APPLICATION_URL?>">" class="linkActive"><i class="icon-home icon-white"></i> Take Me Home</a>
      </div>
    </div>
    
  </div>
</div>
</div><?php */?>
 

<h1><?php echo 'An error occurred'; ?></h1>
<h2><?php echo $this->message; ?></h2>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
<hr/>
<h2><?php echo 'Additional information' ?>:</h2>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
    <dt><?php echo 'File' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt><?php echo Message ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
    </dd>
    <dt><?php echo 'Stack trace' ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    if ($e) :
?>
<hr/>
<h2><?php echo 'Previous exceptions' ?>:</h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?php echo get_class($e); ?></h3>
        <dl>
            <dt><?php echo 'File' ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
            </dd>
            <dt><?php echo 'Message' ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
            </dd>
            <dt><?php echo 'Stack trace' ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3><?php echo 'No Exception available' ?></h3>

<?php endif ?>

<?php endif ?>
