<link href="<?php echo SITE_HTTP_URL?>/public/plugins/Bootstrap-Multiselect/dist/css/bootstrap-multiselect.css" media="screen" rel="stylesheet" type="text/css">
<style type="text/css">
ul#info_ul span {
	color:#e35b5a;
	font-weight:bold;
}
.widget-wrap {
	min-height:auto
}
.label_container label{display:block;}
.paddleft0 {
    padding-left: 0;
}
.paddright0 {
    padding-right: 0;
}
@media (max-width: 767px) {
	.lastelem{padding-left:0;padding-right:0;}
}
</style>


    <div class="page-header filled full-block light">
        <div class="row">
            <div class="col-md-12">
            	<h2><i><span class="<?php echo $this->page_icon ?>"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
            </div>
        </div>
    </div>
    
    <div class="widget-wrap">
        <div class="widget-container">
            <div class="widget-content">
            		
                    <form action="" method="post" class="profile_form" enctype="multipart/form-data" id="profileFormDiv">
                   		<?php /*?><?php echo $this->renderForm($this->form);?> <?php */?>
						 <div class="col-sm-6 form-group">
                          <label for="Amount">Amount(<?php echo PRICE_SYMBOL?>)</label>
                        	
                            <?= $this->formElement($form->get('site_plan_price'))?>
                          </div>
                          <div class="col-sm-6 form-group">
                         	<label>If total investment is under <?php echo PRICE_SYMBOL?><?php echo $this->SITE_CONFIG['site_plan_price']?></label>
                           <?= $this->formElement($form->get('site_under_amount'))?>
                         </div>
                          <div class="clearfix"></div>
                                <?php if(!empty($this->investing_type)){
									foreach($this->investing_type as $invKey=>$invValue){?>
										<div class="col-sm-6 form-group">
                         				<label>If total investment is under <?php echo PRICE_SYMBOL?><?php echo $this->SITE_CONFIG['site_plan_price']?> + <?php echo $invValue['inv_ty_title']?></label>
                          			  	<?= $this->formElement($form->get('site_under_'.$invValue['inv_ty_slug']))?>
                         				</div>
                                        <div class="col-sm-6 form-group">
                         				<label>If total investment is over <?php echo PRICE_SYMBOL?><?php echo $this->SITE_CONFIG['site_plan_price']?> + <?php echo $invValue['inv_ty_title']?></label>
                          			  		<?= $this->formElement($form->get('site_over_'.$invValue['inv_ty_slug']))?>
                         				</div>
                                         <div class="clearfix"></div>
								<? 	}
									?>
									
								<? }?>
								
						 
                         
                          <div class="col-sm-6 form-group">
                         	<label>If total investment is over <?php echo PRICE_SYMBOL?><?php echo $this->SITE_CONFIG['site_plan_price']?></label>
                            <?= $this->formElement($form->get('site_over_amount'))?>
                         </div>
                    
                    	<div class="clearfix">&nbsp;</div>
                        <div class="clearfix">&nbsp;</div>	
                    	<div class="text-center"><button type="submit" class="btn site-btn SiteButton">Submit</button></div>
                        <div class="clearfix"></div>
                    </form>
                     
                 </div>
        </div>
    </div>
    
<script type="text/javascript" src="<?php echo SITE_HTTP_URL?>/public/plugins/Bootstrap-Multiselect/dist/js/bootstrap-multiselect.js"></script>
<script>
$(function(){
		
		var allElements_search={"site_under_amount":"Select Plan","site_under_investing_myself":"Select Plan","site_over_investing_myself":"Select Plan","site_under_employer_plan":"Select Plan","site_over_employer_plan":"Select Plan","site_under_investment_advisor":"Select Plan","site_over_investment_advisor":"Select Plan","site_over_amount":"Select Plan"};
	$.each(allElements_search,function(index, element){
		
		  $('#'+index).multiselect({
				includeSelectAllOption: true,
				nonSelectedText:element,
				buttonClass:"multiPlan form-control text-left",
				buttonWidth:"100%",
				maxHeight:"300",
				onChange: function(option, checked, select) {
					if($('#'+index).next(".btn-group").find("li").hasClass("active")){
						/*$('#'+index).parents('.lastelem').find(".multiProperty").css('border-color','#ccc');*/
						
						$('#'+index).parents().parents().removeClass("has-error");
					     $('[for="'+index+'"]').remove();
					}
					
				},
				onSelectAll: function(option) {
					
					$('#'+index).parents().parents().removeClass("has-error");
					$('[for="'+index+'"]').remove();
					
				},
				onDeselectAll : function(option){
					
				}
				
   		 });
		  
	});
});
</script>
