<style type="text/css">
ul#info_ul span {
	color:#e35b5a;
	font-weight:bold;
}
.widget-wrap {
	min-height:auto
}
.label_container label{display:block;}
.paddleft0 {
    padding-left: 0;
}
.paddright0 {
    padding-right: 0;
}
.lab_return_type ~ label {
 margin-right:15px !important;
}

@media (max-width: 767px) {
	.lastelem{padding-left:0;padding-right:0;}
}
</style>


    <div class="page-header filled full-block light">
        <div class="row">
            <div class="col-md-12">
            	<h2><i><span class="<?php echo $this->page_icon ?>"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
            </div>
        </div>
    </div>
    
    <div class="widget-wrap">
        <div class="widget-container">
            <div class="widget-content">
            		
                    <form action="" method="post" class="profile_form" enctype="multipart/form-data" id="profileFormDiv">
                   		<?php /*?><?php echo $this->renderForm($this->form);?> <?php */?>
						
						<?php if(true){?>
						<?php if(!empty($this->investing_reason)){
							foreach($this->investing_reason as $inv_opt=>$inv_key){
								if($inv_key['inv_res_id']!=5){
								
								?>
                                <h4 class="text-center"><?php echo $inv_key['inv_res_title']?></h4>
                                 <div class="clearfix"></div>
                                 <div style="display:table;width:100%;">
								 <?php
								 if(!empty($this->investing_reason_configs)){
									 foreach($this->investing_reason_configs as $key=>$values){
										 if($values['inv_res_config_resid']==$inv_key['inv_res_id']){
										 	if($values['inv_res_config_isreturn']=='1'){?>
												<div style="display: table-row;"></div>
											<? }
										 ?>
                            				  <div style="display:table-cell;vertical-align:top;">
                                <div class="col-sm-12">
                                 <label for="<?php echo $values['inv_res_config_title']?>" style="font-weight:bold;font-size:15px;"><?php echo $values['inv_res_config_title']?></label>
                                </div>
                                
								<div class="col-sm-12">
                                                 <div class="form-group">
                                                      <?= $this->formElement($form->get( $values['inv_res_config_resid'].'['.strtolower($values['inv_res_config_title']).']'))?>
                                                       
                                              		 </div>
                                </div>
                                </div>
                                <? if($values['inv_res_config_isreturn']=='1'){?>
                                   <div style="display:table-cell;vertical-align:top;">
                                   	<div class="col-sm-12">
                                    	<label style="font-weight:bold;font-size:15px;" class="lab_return_type">Return Type</label>
                                        <div class="clearfix"></div>
                                         <?= $this->formElement($form->get( $values['inv_res_config_resid'].'[returntype]'))?>
                                    </div>
                                   </div>
                                <? }?>
                                			
                             			  
									 <? }}
								 }?>
                            	 <div class="clearfix"></div>
                                </div>    
                               
                                <? }else{
									?>
                                     <h4 class="text-center"><?php echo $inv_key['inv_res_title']?> Options</h4>
                                     <div class="clearfix"></div>
									<? 
									
									foreach($this->investing_reason_option as $inv_res_opt=>$inv_res_key){?>
									<div class="col-sm-3">
                                 	<label for="<?php echo $inv_res_key['inv_res_opt_restype']?>" style="font-weight:bold;font-size:15px;margin-top:30px;"><?php echo $inv_res_key['inv_res_opt_restype']?></label>
                               		 </div>
                                	<div class="col-sm-9">
                                    <div style="display:table;width:100%;">
                                     <?php
								 
								  if(!empty($this->investing_reason_configs)){
									 foreach($this->investing_reason_configs as $key=>$values){
										 if($values['inv_res_config_isreturn']=='1'){?>
												<div style="display: table-row;"></div>
											<? }
										 if(($values['inv_res_config_resid']==$inv_key['inv_res_id']) && ($values['inv_res_config_optid']==$inv_res_key['inv_res_opt_id'])){
										 ?>
                                 <div style="display:table-cell;vertical-align:top;">
                            	<div class="col-sm-12">
                                 <label for="<?php echo $values['inv_res_config_title']?>"><b><?php echo $values['inv_res_config_title']?></b></label>
                                </div>
                                
								<div class="col-sm-12">
                                                 <div class="form-group">
                                                      <?= $this->formElement($form->get( $values['inv_res_config_resid'].'['.$values['inv_res_config_optid'].']'.'['.strtolower($values['inv_res_config_title']).']'))?>
                                                       
                                              		 </div>
                                </div>
                                </div>
                                 <? if($values['inv_res_config_isreturn']=='1'){?>
                                   <div style="display:table-cell;vertical-align:top;">
                                   	<div class="col-sm-12">
                                    	<label style="font-weight:bold;font-size:15px;" class="lab_return_type">Return Type</label>
                                        <div class="clearfix"></div>
                                         <?= $this->formElement($form->get( $values['inv_res_config_resid'].'['.$values['inv_res_config_optid'].']'.'[returntype]'))?>
                                    </div>
                                   </div>
                                <? }?>
                              
                                
                               <? 
									 }
									 
									 }
								 }?>
                                    
                                               
                                                     </div>
                                </div>
								
									<? }
								}?>
                                <div style="border-bottom:1px solid grey;">&nbsp;</div>
							<? }
							?>
							
						<? }?>
                        		 
                       <? }?>
                    
                    	<div class="clearfix">&nbsp;</div>
                        <div class="clearfix">&nbsp;</div>	
                    	<div class="text-center"><button type="submit" class="btn site-btn SiteButton">Submit</button></div>
                        <div class="clearfix"></div>
                    </form>
                     
                 </div>
        </div>
    </div>
    

