<div class="makediv overview_box" style="margin-top:0;">
<div class="strate_box_top">
<div class="strate_box_top_inner">
<div class="strate_box_top_panel" style="background: rgba(252, 209, 22, 0.57);">
<div class="registration-box-bg" style="margin-top:60px;">
	<div class="text-center"><h1>Forgot Password</h1></div>
	<div style="margin-top:60px;">
    	<div class="loginbox" style="min-height:280px">
        	<div class="text-left makediv">
            
            	
                	
            		<form action="" method="post" class="profile_form" enctype="multipart/form-data" id="registrationForm">
                    	<div class="row">
                        	<div class="col-md-12">
                            	<div class="form-group">
                                	<label for="user_email">Email address</label>
                            		<?php echo $this->formElement($form->get('user_email'))?>
                                </div>
                                
                                <div class="form-group text-center">
                                	<button class="btn SiteButton" type="submit">Submit</button>
                                </div>
                              
                                <div class="form-group">
                                	<a href="<?php echo $this->url('register')?>" class="pull-left nblink"><b>Sign Up</b></a>
                                    <a href="<?php echo $this->url('login')?>" class="pull-right nblink"><b>Login</b></a>
                                </div>
                            </div>
                        </div>
                    </form>
            	</div>
            
        </div>
        <div class="clearfix"></div>
    </div>
</div>
</div>
</div>
</div>
</div>


