<div class="makediv overview_box" style="margin-top:0;">
<div class="strate_box_top">
<div class="strate_box_top_inner">
<div class="strate_box_top_panel" style="background: rgba(252, 209, 22, 0.57);">
<div class="registration-box-bg" style="margin-top:20px;">
	<div class="text-center"><h1>Reset Password</h1></div>
    <p class="register-desc">Enter your new details and your password will be reseted. Kindly ignore if you have not asked for password reset.</p>
	<div style="margin-top:60px;">
    	<div class="loginbox" style="min-height:280px">
        	<div class="text-left makediv">
            
            	
                	
            		<form action="" method="post" class="profile_form" enctype="multipart/form-data" id="registrationForm">
                    	<div class="row">
                        	<div class="col-md-12">
                            	<div class="form-group">
                                	<label for="user_password">Enter Password</label>
                            		<?php echo $this->formElement($resetForm->get('user_password'))?>
                                </div>
                                <div class="form-group">
                                	<label for="user_rpassword">Confirm new password</label>
                            		<?php echo $this->formElement($resetForm->get('user_rpassword'))?>
                                </div>
                                <div class="form-group text-center">
                                	<button class="btn SiteButton" type="submit">Submit</button>
                                </div>
                              
                                
                            </div>
                        </div>
                    </form>
            	</div>
            
        </div>
        <div class="clearfix"></div>
    </div>
</div>
</div>
</div>
</div>
</div>