
<div class="mws-panel grid_8">
<?php 
	if ($con==1){
?>
    <div style="height:30px;background:#339933;">
    	<img src="<?=APPLICATION_URL?>data/uploads/yes.png" alt="" width="30"  border="0"/>
    	<span style="color:#ffffff;font-size:16px;"><? echo "Password Saved successfully !!"?></span>
    </div>
<?php
}elseif($con==3){
?>
    <div style="height:30px;background:#339933;">
    	<img src="<?=APPLICATION_URL?>data/uploads/yes.png" alt="" width="30"  border="0"/>
    	<span style="color:#ffffff;font-size:16px;"><? echo "Passowrd do not match!!"?></span>
    </div>
<?php 
}
?>
    <div class="mws-panel-header">
    	<span class="mws-i-24 i-check">Change Password</span>
    </div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'changepassword')));
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
?>
    <div class="mws-panel-body">
    	<div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
        <div class="mws-form-inline">
        	<div style="height:30px;"></div>
            <div class="mws-form-row">
            	<label><span style="color:#000000;font-size:16px;margin-left:10px;">Username :</span><span style="margin-left:100px;"><? echo $this->formRow($form->get('admin_username')) . PHP_EOL; ?></span></label>
            
            </div>
        	<div style="height:15px;"></div>
            <div class="mws-form-row">
        		<label><span style="color:#000000;font-size:16px;margin-left:10px;">New Password :</span><span style="margin-left:70px;"><? echo $this->formRow($form->get('admin_new_password')) . PHP_EOL; ?></span></label>
        	</div>
        	<div style="height:15px;"></div>
        	<div class="mws-form-row">
        		<label><span style="color:#000000;font-size:16px;margin-left:10px;">Confirm Password :</span><span style="margin-left:45px;"><? echo $this->formRow($form->get('admin_confirm_password')) . PHP_EOL; ?></span></label>
        	</div>
        </div>
    	<div style="height:15px;"></div>
    	<div>
    		<span style="margin-left:185px;"><? echo $this->formInput($form->get('submit')) . PHP_EOL; ?></span>
    	</div>
    </div> 
<?php
echo $this->form()->closeTag($form) . PHP_EOL;
?>  	
</div>