<div class="page-header filled full-block light">
	<h2><i><span class="<?php echo $this->page_icon ?>"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
</div>
<div class="widget-wrap">
	
  <div class="widget-container">
  	
    <div class="widget-content">
    <?php /*?><div id="flash-message" class="alert alert-dismissable" style="display:none; margin:20px;"></div><?php */?>
     
        <table id="sample_1" class="table table-striped table-bordered table-hover dataTable">
          <thead>
            <tr>
              <th>S.No.</th>
              <th>User Name</th>
              <th>Appointment Date</th>
              <th>Appointment Time</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
        
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
var consult='<?php echo $this->consult?>';
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": false,
		"responsive": true,
 		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/get-consulting-request/"+consult ,
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [1,2] },
 		 
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnInitComplete": function (oSettings, json) { re_init();}
	} );
});


</script>