<?php 
$pageData = $AbstractModel->Super_Get("pages","page_id='15'","fetch");

?>
<div class="footerDiv">
	<div class="container">
    	<div class="row footer-logo-main">
    	<div class="col-xs-12 col-sm-6 col-lg-4 footer-logo-outer">
        	<div class="footer-logo-box">
            <div class="footer-logo">
            	<img src="<?php echo HTTP_IMG_PATH?>/footer_logo.png" />
            </div>
        	<div class="footer-bottom"><?=$this->SITE_CONFIG['site_footer_text']?>
            </div>
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-6 col-lg-6 footer-all-links">
        
     
            <ul class="footnavLi text-left footnavleftLi">
            <li><a  href="<?=SITE_HTTP_URL?>" <?php echo ($this->pageTag=='home')?"class='active afooterNav'":"class='afooterNav'"?>>Home</a></li>
            <li><a  href="<?=$this->url('front_overview')?>"  <?php echo ($this->pageTag=='overview')?"class='active afooterNav'":"class='afooterNav'"?>>The Regal Way</a></li>
            <li><a  href="<?=$this->url('front_services')?>" <?php echo ($this->pageTag=='services')?"class='active afooterNav'":"class='afooterNav'"?>>Services</a></li>
            <li><a href="<?=$this->url('front_contact')?>" <?php echo ($this->pageTag=='contact')?"class='active afooterNav'":"class='afooterNav'"?>>Contact Us</a></li>
            <li><a href="<?=$this->url('front_career')?>" <?php echo ($this->pageTag=='career')?"class='active afooterNav'":"class='afooterNav'"?>>Careers</a></li>
            </ul>
            <ul class="footnavLi text-left footnavrighttLi">
            <li><a   href="<?=$this->url('front_resources')?>" <?php echo ($this->pageTag=='resources')?"class='active afooterNav'":"class='afooterNav'"?>>Resources</a></li>
            <li><a  href="<?=$this->url('front_faq')?>" <?php echo ($this->pageTag=='faq')?"class='active afooterNav'":"class='afooterNav'"?>>FAQs</a></li>
            <li><a  href="<?=$this->url('front_blessings')?>" <?php echo ($this->pageTag=='blessings')?"class='active afooterNav'":"class='afooterNav'"?> class="afooterNav">Blessings</a></li>
            <li><a   href="<?=$this->url('front_terms')?>" <?php echo ($this->pageTag=='terms')?"class='active afooterNav'":"class='afooterNav'"?>>Terms & Policies</a></li>
            <li><a href="<?=$this->url('front_pricing')?>" <?php echo ($this->pageTag=='pricing')?"class='active afooterNav'":"class='afooterNav'"?>>Pricing</a></li>
            </ul>
        </div>
        <div class="col-sm-12 col-lg-2 footRight">
        	<div class="social_icons">
            
            	<div class="social_icons_tw">
                	<a target="_blank" href="<?=$this->SITE_CONFIG['twitter_link']?>"><span class="fa fa-twitter"></span></a>
                </div>
                
                <div class="social_icons_gplus">
                	<a target="_blank" href="<?=$this->SITE_CONFIG['gplus_link']?>"><i class="fa fa-google-plus fa-fw"></i></a>
                </div>
                
                <div class="social_icons_fb">
                	<a target="_blank" href="<?=$this->SITE_CONFIG['facebook_link']?>"><span class="fa fa-facebook"></span></a>
                </div>
                
                <div class="social_icons_in">
                	<a target="_blank" href="<?=$this->SITE_CONFIG['linkedin_link']?>"><span class="fa fa-linkedin"></span></a>
                </div>
            </div>
            <div class="text-right">
            <div class="footer_text_head"><?php echo $this->SITE_CONFIG['site_name'];?> &copy; <?php echo date("Y")?></div>
        	<div class="footer_sub_text_head">all rights reserved.</div>
            </div>
        </div>
        
        <div class="clearfix">&nbsp;</div>
        <div class="clearfix">&nbsp;</div>
        <div class="col-sm-12 footerEleBlock">
        <?php echo $pageData['page_content'];?>
        </div>
        </div>
        
    </div>
</div>