<div id="grad" class="animated fadeIn element_block">
<div class="makediv relative">
<?php echo $this->render("auth-acl/profile/_profile_side_bar.phtml");?>


	<div class="main-content container" >

		<div class="menu">
        		<div class="ProfileConDiv">
					<div class="panel-body" align="left">
                    		
                            <div class="col-sm-12" style="max-width:500px;margin:0 auto;">
                            	<div class="contentborder">
                    				 <h3><b><i class="fa fa-lock ocolor contenticon" aria-hidden="true"></i>&nbsp;Change Password</b></h3>
                   				</div>
                                
                               
                                
                     			<?php echo $this->renderForm($this->form);?>
                     		</div>
                      </div>
				</div>
				<p class="clearfix">&nbsp;</p>
		</div>

	</div>
    </div>
   </div>