
<div id="grad" class="animated fadeIn element_block">
<div class="makediv relative">
<?php echo $this->render("auth-acl/profile/_profile_side_bar.phtml"); ?>


	<div class="main-content container" >

		<div class="menu">
        
				<form action="" method="post" class="profile_form" enctype="multipart/form-data" id="profileFormDiv">
                   		
                         <div class="ProfileConDiv">
                         
                         <div class="panel-body" align="left">
                         	<div class="col-sm-8">
                            <div class="row contentborder">
                    				<h3 class="col-sm-12 "><b><i class="fa fa-info-circle ocolor contenticon" aria-hidden="true"></i>&nbsp;About</b></h3>
                   			</div>
                         	<div class="clearfix">&nbsp;</div>
                          
                    
                                   <div class="makediv">
                                    <div class="col-sm-6 col-xs-12 lastelem form-group paddleft0">
                                        <label for="user_first_name">First Name</label>
                                        <?php echo $this->formElement($form->get('user_first_name'))?>
                                    </div>
                                    
                                    <div class="col-sm-6 col-xs-12 lastelem form-group paddright0">
                                        <label for="user_last_name">Last Name</label>
                                        <?php echo $this->formElement($form->get('user_last_name'))?>
                                    </div>
                                </div>
                                 <div class="makediv">
                                 <div class="col-sm-6 col-xs-12 form-group lastelem paddleft0">
                                        <label for="user_email">Email Address</label>
                                        <?php echo $this->formElement($form->get('user_email'))?>
                                    </div>
                                  
                                   <div class="col-sm-6 col-xs-12 form-group lastelem paddright0">
                                          <label for="user_location">Location</label>
                                        <?php echo $this->formElement($form->get('user_location'))?>
                                         <?php echo $this->formElement($form->get('user_loc_latitude'))?>
                                          <?php echo $this->formElement($form->get('user_loc_longitude'))?>
                                    </div>  
                                    
                                </div>
                                                
                                   <div class="makediv">
                                 <div class="col-sm-6 col-xs-12 form-group lastelem paddleft0">
                                        <label for="user_annual_income">Annual Income(<?php echo PRICE_SYMBOL?>)</label>
                                        <?php echo $this->formElement($form->get('user_annual_income'))?>
                                    </div>
                                  
                                   <div class="col-sm-6 col-xs-12 form-group lastelem paddright0">
                                          <label for="user_emp_status">Employment Status</label>
                                        <?php echo $this->formElement($form->get('user_emp_status'))?>
                                    </div>  
                                    
                                </div>
                                                      
                                                 
                                                
                                                
                                                
                                                
                                 
                            <div class="clearfix">&nbsp;</div>                 
                             </div>              
                               <div class="col-sm-4 text-center">   
                               		<div class="col-sm-12 contentborder">
                    			<div class="row">
                  					<h3><b><i class="fa fa-info-circle ocolor contenticon" aria-hidden="true"></i>&nbsp;Profile Image</b></h3>
                   				</div>
                    		</div>          
                          		   <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-preview thumbnail PaddingZero" style="max-width: 250px; max-height: 250px;min-height:20px;padding:0px;">
                            <img src="<?php echo getUserImage($this->userData['user_image'],"thumb")?>" alt=""/>
                        </div>
                        
                        <div>
                            <span class="btn btn-xs btn-info btn-file">
                                <span class="fileinput-new"> Select Profile Image </span><?php /*?><span class="OrangeStar">*</span><?php */?>
                                
                                <span class="fileinput-exists"> Change </span>
                                <?php echo $this->formElement($form1->get('user_image'))?>
                            </span>
                            
                            
                            <input type="hidden" name="rotate" id="rotate" value="0" />
                            <a href="#" class="btn btn-xs btn-danger default fileinput-exists" data-dismiss="fileinput">Remove</a><br />
                            <small style="color: #2a2c2e;margin-left: 10px;">A visible photo of your face is required.</small>
                        </div>
					</div>   
                    			</div>
                    		</div>            
                        				<div class="text-center"><?php echo $this->formElement($form->get('bttnsubmit'))?></div>    
                     	 </div>
                       
                    
                    	
                    
					<p class="clearfix">&nbsp;</p>
                    	
                    </form>
			

		</div>

	</div>
    </div>
   </div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo GOOGLE_MAP_API_KEY?>&libraries=places&sensor=false">
</script>
<script>
	
	$(document).ready(function() {
	google.maps.event.addDomListener(window, 'load', initialize);
	});
function initialize() {
        var input = document.getElementById('user_location');
        var autocomplete = new google.maps.places.Autocomplete(input);
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
        var place = autocomplete.getPlace();
        document.getElementById('user_loc_latitude').value = place.geometry.location.lat();
        document.getElementById('user_loc_longitude').value = place.geometry.location.lng();
        });
 }
 </script>