
  <div class="page-header filled full-block light">
    <div class="row">
      <div class="col-md-12">
       <h2><i><span class="<?php echo $this->page_icon ?>"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
      </div>
    </div>
  </div>
  <div class="widget-wrap">
    <div class="widget-container">
      <div class="widget-content">
        <form method="post" action="<?php echo ADMIN_APPLICATION_URL?>/removepages"  onsubmit="return checkSelects();" >
        <table id="sample_1" class="table table-striped table-bordered table-hover dataTable">
          <thead>
            <tr>
              <th width="6%">S No.</th>
              <th>Title</th>
              <th>Subject</th>
              <th width="15%">Last Modified</th>
              <th  width="10%">Action</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </form>
      </div>
    </div>
  </div>





 


<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": false,
		"responsive": true,
 		"sAjaxSource": "<?php echo APPLICATION_URL.'/'.BACKEND?>/getemailtemplate" ,
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [1,3,4] },
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnInitComplete": function (oSettings, json) { re_init();}
	} );
});
</script>