<div class="page-header filled full-block light">
    <div class="row text-center">
        <div class="col-md-12 col-sm-12">
        	<h2><i><span class="fa fa-home"></span>&nbsp;<?php echo $this->pageHeading ?></i></h2>
        	<p><i><b>Administrator dashboard panel</b></i></p>
        </div>
        
    </div>
</div>

<div class="row">
	<div class="col-md-4">
			<div class="w_bg_teal stats-chart-container w_bg_cyan AdvBlue">
                	<a href="<?php echo ADMIN_APPLICATION_URL.'/pages'?>"> 
                		<div class="tableBlock">
                    		<div class="tablechildBlock">
                    			<h2 class="Count">
                   			 		<i class="fa fa-file-text-o"></i> 
                    				<label><?php echo $this->pages_count?></label>
                    
                  			  </h2>
                   		 </div>
                    </div>
                </a>
            </div>
        	<div class="stats-widget">
            <div class="widget-header text-center AdvDashboardHeading">
                <h3><a href="<?php echo ADMIN_APPLICATION_URL.'/pages'?>" style="color:inherit;text-decoration:none;"> Pages</a></h3>
                
            </div>
            
            
        </div>
    </div>
    
   <div class="col-md-4">
			<div class="w_bg_teal stats-chart-container w_bg_cyan AdvBlue">
                	<a href="<?php echo ADMIN_APPLICATION_URL.'/emailtemplate'?>"> 
                		<div class="tableBlock">
                    		<div class="tablechildBlock">
                    			<h2 class="Count">
                   			 		<i class="fa fa-envelope"></i> 
                    				<label><?php echo $this->email_count?></label>
                    
                  			  </h2>
                   		 </div>
                    </div>
                </a>
            </div>
        	<div class="stats-widget">
            <div class="widget-header text-center AdvDashboardHeading">
                <h3><a href="<?php echo ADMIN_APPLICATION_URL.'/emailtemplate'?>" style="color:inherit;text-decoration:none;"> Email Templates</a></h3>
                
            </div>
            
            
        </div>
    </div>
    
   
    
    <div class="col-md-4">
			<div class="w_bg_teal stats-chart-container w_bg_cyan AdvBlue">
                	<a href="<?php echo ADMIN_APPLICATION_URL.'/faqs'?>"> 
                		<div class="tableBlock">
                    		<div class="tablechildBlock">
                    			<h2 class="Count">
                   			 		<i class="fa fa-question-circle"></i> 
                    				<label><?php echo $this->faq_count?></label>
                    
                  			  </h2>
                   		 </div>
                    </div>
                </a>
            </div>
        	<div class="stats-widget">
            <div class="widget-header text-center AdvDashboardHeading">
                <h3><a href="<?php echo ADMIN_APPLICATION_URL.'/faqs'?>" style="color:inherit;text-decoration:none;">FAQ</a></h3>
                
            </div>
            
            
        </div>
    </div>
    
    
    <div class="col-md-4">
			<div class="w_bg_teal stats-chart-container w_bg_cyan AdvBlue">
                	<a href="<?php echo ADMIN_APPLICATION_URL.'/plans'?>"> 
                		<div class="tableBlock">
                    		<div class="tablechildBlock">
                    			<h2 class="Count">
                   			 		<i class="fa  fa-paper-plane"></i> 
                    				<label><?php echo $this->plan_count?></label>
                    
                  			  </h2>
                   		 </div>
                    </div>
                </a>
            </div>
        	<div class="stats-widget">
            <div class="widget-header text-center AdvDashboardHeading">
                <h3><a href="<?php echo ADMIN_APPLICATION_URL.'/plans'?>" style="color:inherit;text-decoration:none;">Investment Plans</a></h3>
                
            </div>
            
            
        </div>
    </div>
    
    <div class="col-md-4">
			<div class="w_bg_teal stats-chart-container w_bg_cyan AdvBlue">
                	<a href="<?php echo ADMIN_APPLICATION_URL.'/users'?>"> 
                		<div class="tableBlock">
                    		<div class="tablechildBlock">
                    			<h2 class="Count">
                   			 		<i class="fa  fa-users"></i> 
                    				<label><?php echo $this->user_count?></label>
                    
                  			  </h2>
                   		 </div>
                    </div>
                </a>
            </div>
        	<div class="stats-widget">
            <div class="widget-header text-center AdvDashboardHeading">
                <h3><a href="<?php echo ADMIN_APPLICATION_URL.'/users'?>" style="color:inherit;text-decoration:none;">Users</a></h3>
                
            </div>
            
            
        </div>
    </div>
    
    <?php /*?><div class="col-md-4">
        <div class="stats-widget stats-widget ">
            <div class="widget-header text-center AdvDashboardHeading">
                <h3>Role</h3>
                
            </div>
            
            <div class="w_bg_teal stats-chart-container w_bg_cyan AdvBlue">
                <a style="color:#ffffff; text-decoration:none" href="<?php echo ADMIN_APPLICATION_URL.'/role'?>"> 
                	<h2 class="Count"><i class="fa fa-tasks"></i> <label><?php echo $this->role_count?></label></h2>
                </a>
            </div>
        </div>
    </div><?php */?>
    
    
    
    
    
    
</div>