
<div style="max-width:400px;padding:20px;margin-top:100px;" class="center-block">
  <h1 class="center" style="margin-top:20px;">404 Page Not Found</h1>
 <div class="center row-fluid index_main_div" >
  <div class="span12">
    <div class="row-fluid page-404" style="margin-top:10px;margin-bottom:30px;">
      <div class="span5 number">  </div>
      <div class="span7 details">
        <h2>Opps, You're lost.</h2>
        <p> We can not find the page you're looking for.</p>
        <a href="<?=ADMIN_APPLICATION_URL?>" class="linkActive"><i class="icon-home icon-white"></i> Take Me Dashboard</a>
      </div>
    </div>
    
  </div>
</div>
</div>

