<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
</head>


<style type="text/css">
.glyph {
    fill: currentColor;
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    position: relative;
    text-align: center;
    vertical-align: middle;
    width: 70%;
    height: 70%;
}
</style>
       

<script type="text/javascript">
$(document).ready(function(){
	// demo.initChartist();
	$.notify({
		icon: 'pe-7s-gift',

	},{
		type: 'info',
		timer: 4000
	});

});
</script>

    

</html>
