<style>
body,html{height:100%;}
</style>
<div style="display: table;width: 100%;height: 100%; background-image: url('<?php echo HTTP_IMG_PATH ?>/error.jpg');background-repeat: no-repeat;background-size: cover;">


<div style="display: table-cell;
    vertical-align: middle;">
	<div class="text-center" style="margin-top:-8%;">
    			
    			<h1 style="font-size:70px;">404</h1>
    			<h3 style="margin-bottom:10px;">Page Not Found</h3>
            	<h4 >Whoops, You're lost.</h4>
			</div>
</div>
</div>