<script type="application/javascript" src="<?=APPLICATION_URL?>/public/js/mediaplayer/jwplayer.js"></script>
<script src="<?php echo SITE_HTTP_URL?>/public/js/highcharts.js"></script>
<style>
#invest_amount {
  min-width:50px!important;
  max-width:99.99%!important;
  transition: width 0.25s;
  text-align:center;
}
</style>
<?php  if(false){?>
<div class="business_block">
	<div class="business_block_head">
    	<div class="business_block_head_text">
            <div class="head-one">TOGETHER WE CAN ACHIEVE MORE</div>
            <div class="head-two">LETS TALK BUSINESS</div>
            <div class="clearfix"><a class="head_join_btn">Join Now</a></div>
         </div>
    </div>
</div>

<div class="container support_company_box">
		<div class="col-lg-6 col-sm-7">
        	<div class="support_head">Welcome to the </div>
            <div class="support_head">Best Business </div>
            <div class="support_head">Support Company</div>
           
            <div class="service_text_box">
            <div class="service_text">
            	Economic services provided by the <br />finance industry, which encompasses a<br /> broad range of businesses that manage<br />
                money including credit unions.
            </div>
            </div>
            <div class="clearfix service_text_boxAbout" >
            	<a class="support_about">More About us</a>
            </div>
        </div >
        <div class="col-lg-6 col-sm-5">
        	<img src="{img_url}/business_company.png" class="img-responsive"  style="margin:0 auto;"/>
        </div>
</div>
<div class="clearfix">&nbsp;</div>
<div class="makediv" style="background-color: #f1f1f1;">
<div class="container">
	<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    	<div class="row stats_block">
        <div class="stats_block_top">
          <div class="stats_block_inner">
          <div class="stats_block_box_first">
          	<div class="stats_content">01</div>
           		<div class="stats_content_head">Make Business <br />Strategy</div>
             </div>
       		<div class="block_text_first"> We will help you set new business priorities, outline <br />plans for growth, determine a product roadmap or <br /> plan your investment decisions.</div>
            </div>
            </div>
        </div>
    </div>
    
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    	<div class="row stats_block stats_middle_block">
        <div class="stats_block_top">
          <div class="stats_block_inner">
          <div class="stats_block_box">
          	<div class="stats_content">02</div>
           		<div class="stats_content_head">Company of <br />Professionals</div>
             </div>
       		<div class="block_text"> Competence, Reliability, Honesty, Integrity – these definitions characterize our employees in the best way.</div>
            </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    	<div class="row stats_block">
        <div class="stats_block_top">
          <div class="stats_block_inner">
          <div class="stats_block_box_last">
          	<div class="stats_content">03</div>
           		<div class="stats_content_head">We Love Our <br />Clients</div>
             </div>
       		<div class="block_text_last"> Success of any organization depends on customers. That is why the first rule of our business is to retain clients and build a loyal relationship with them.</div>
            </div>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

<div class="makediv strate_box">
	<div class="strate_box_top">
    <div class="strate_box_top_inner">
           <div class="strate_box_top_panel">
            <div class="strate_box_top_head">our main goal –</div>
            <div class="strate_box_top_sub_head">Strategies That Work</div>
            <div class="strate_box_top_sub_text">
                Economic services provided by the finance industry, which encompasses a broad range of businesses that manage money, including credit unions.
            </div>
            <div><a class="find_out_btn">Find out more</a></div>
            </div>
    </div>
    </div>
</div>
<div class="makediv one-edge-shadow">

	<div class="col-lg-5 col-sm-6 " style="padding:0">
    		<div class="investment_block_left" >	
           
            <div class="investment_block_container">
            		<div class="investment_block_box">
            		<div class="investment_block_comt_head">Our commitment</div>
                    <div class="investment_block_comt_sub_head">The new way means we work for you.</div>
                    <div class="investment_block_comt_full_text">
                    	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                    </div>
                   
                    <div class="investment_out_btn_outer"><a class="investment_out_btn">Start your investment plan</a></div>
                    </div>
                </div>
            </div>
    </div>
    <div class="col-lg-7 col-sm-6" >
    		<div class="row investment_block">
            </div>
    </div>
</div>

<div class="makediv return_block text-center">
<div class="container">
	<div class="row">
	<div class="return_block_head">I would like to invest <span>5000 USD</span></div>
    <div class="return_block_sub_head">*Your Projected Returns are</div>
    <div class="text-center return_block_graph">
    	<img src="{img_url}/graph.png"  class="img-responsive" style=" margin: 0 auto;"/>
    </div>
    <div class="prospering_outer">
    	<a class="prospering_btn">Start Prospering</a>
    </div>
    
    <div class="prospering_bottom_txt">
    	*all projections are calculated using historical performance data, actual performance may vary
    </div>
    </div>
    </div>
</div>
<? }?>

<style>


.business_block{background: url(<?php echo HTTP_HOME_IMAGES_PATH?>/<?php echo $this->page_media[0]['hom_med_value']?>);}



.stats_block{padding-top:40px;padding-bottom:40px;}
</style>

<?php ?>
<?php echo $this->page_content?>
<div class="makediv return_block text-center">
<div class="container">
	<div class="row">
	<div class="return_block_head">I would like to invest <input type="text" id="invest_assets" value="5000"/>USD in <input type="text" id="invest_assets_year" value="2"/>Year<span></span></div>
    <div class="return_block_sub_head">*Your Projected Returns are</div>
    <div class="text-center return_block_graph">
    	<div id="assets_container" style="min-width: 310px; height: 400px; margin: 0 auto;max-width:800px;" class="hide"></div>
    </div>
    <div class="prospering_outer">
    	<a class="prospering_btn" href="<?php echo SITE_HTTP_URL?>/register">Start Prospering</a>
    </div>
    
    <div class="prospering_bottom_txt">
    	*all projections are calculated using historical performance data, actual performance may vary
    </div>
    </div>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="clearfix">&nbsp;</div>
</div>
 <?php
$business_support_video =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[2]['hom_med_value'];
$business_support_thumb =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[1]['hom_med_value'];	
$business_strategy_video =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[4]['hom_med_value'];
$business_strategy_thumb =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[3]['hom_med_value'];				
$company_professional_video =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[6]['hom_med_value'];
$company_professional_thumb =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[5]['hom_med_value'];
$client_video_video =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[8]['hom_med_value'];
$client_video_thumb =HTTP_HOME_IMAGES_PATH ."/".$this->page_media[7]['hom_med_value'];
 ?>
					
<script>
var doneTypingInterval = 500; 
var typingTimer1; 
$(document).ready(function(e) {
		var videoWidth='80%';var videoHeight=210;
		jwplayer("div_company_professional_video").setup({
			flashplayer: "<?php echo APPLICATION_URL?>/public/js/mediaplayer/player.swf",
			file: "<?=$company_professional_video?>",
			image: "<?=$company_professional_thumb?>",
			width: videoWidth,
			autostart: false,
			height: videoHeight,
			'controlbar': 'none',
			plugins: 'http://plugins.gitraffic.com/plugins/GirafficJW50Plugin.swf',
		});
		jwplayer("div_business_support_video").setup({
			flashplayer: "<?php echo APPLICATION_URL?>/public/js/mediaplayer/player.swf",
			file: "<?=$business_support_video?>",
			image: "<?=$business_support_thumb?>",
			//width: 482,
			autostart: false,
			//height: 357,
			width: "90%",
			

			'controlbar': 'none',
			plugins: 'http://plugins.gitraffic.com/plugins/GirafficJW50Plugin.swf',
		});
		jwplayer("div_client_video_video").setup({
			flashplayer: "<?php echo APPLICATION_URL?>/public/js/mediaplayer/player.swf",
			file: "<?=$client_video_video?>",
			image: "<?=$client_video_thumb?>",
			width: videoWidth,
			autostart: false,
			height: videoHeight,
			'controlbar': 'none',
			plugins: 'http://plugins.gitraffic.com/plugins/GirafficJW50Plugin.swf',
		});
		jwplayer("div_business_strategy_video").setup({
			flashplayer: "<?php echo APPLICATION_URL?>/public/js/mediaplayer/player.swf",
			file: "<?=$business_strategy_video?>",
			image: "<?=$business_strategy_thumb?>",
			width: videoWidth,
			autostart: false,
			height: videoHeight,
			'controlbar': 'none',
			plugins: 'http://plugins.gitraffic.com/plugins/GirafficJW50Plugin.swf',
		});
		$('#invest_assets_year').keyup(function(e) {
			resizable(document.getElementById('invest_assets_year'),7);
			clearTimeout(typingTimer1);
			typingTimer1 = setTimeout(check_book_type, doneTypingInterval);	
		});
		$('#invest_assets').keyup(function(e) {
    		resizable(document.getElementById('invest_assets'),7);
			clearTimeout(typingTimer1);
  			typingTimer1 = setTimeout(check_book_type, doneTypingInterval);
			
	});
	$('#invest_assets').keydown(function(e) {
		clearTimeout(typingTimer1);
			
	});
		check_book_type();
});	
function check_book_type(){
	var value=$('#invest_assets').val();
	 var invest_assets_year=$('#invest_assets_year').val();
	  // var book_type=this.value;
	   var book_type=2;
	   var type=0;
	 	$.ajax({ 
			  url: baseUrl+"/getpie",
			  type: "POST",
			  async:false,
			// dataType:'json',
			  data: {book_type:book_type,type:type,value:value,invest_assets_year:invest_assets_year},
			  success: function(data){ 
			  	subdata=JSON.parse(data);
				 // console.log(subdata[subdata.length-1]['risk_level']);
			  	var amountdata= subdata[subdata.length-1]['amount'];
			    var general_graph_years=$.parseJSON(subdata[subdata.length-1]['general_graph_years']);
			    var general_graph_amount=$.parseJSON(subdata[subdata.length-1]['general_graph_amount']);
			    var general_graph_project_amount=$.parseJSON(subdata[subdata.length-1]['general_graph_project_amount']);
			    var general_graph_industry_average=$.parseJSON(subdata[subdata.length-1]['general_graph_industry_average']);
			 	var masterArr=[ [], [] ] ;
			 	if(book_type==2){ 
				$('#assets_container').removeClass('hide');
				Highcharts.chart('assets_container', {
				chart: {
        			type: 'area',
					backgroundColor: 'transparent'
    			},
    			title: {
        			text: 'Investable assets'
    			},
    			subtitle: {
        			//text: '<?php echo PRICE_SYMBOL?>'
    			},
    			xAxis: {
					categories: general_graph_years,
					tickmarkPlacement: 'on',
					title: {
						enabled: true,
						text: 'Years'
					}
    			},
   			 yAxis: {
		  			allowDecimals: true,
					title: {
						 enabled: true,
						text: 'Returns on Investment'
					},
		
        			labels: {
            			formatter: function () {
						//return this.value / 1000;
			   			 return this.value;
            			}
        			}
    		},
    		tooltip: {
        		split: true,
       			// valueSuffix: ' millions'
   			 },
    		plotOptions: {
      		  area: {
          		 // stacking: 'normal',
           		  lineColor: '#666666',
            	  lineWidth: 1,
            	  marker: {
                		lineWidth: 1,
                		lineColor: '#666666'
            	 }
       		 }
   		  },
   		 series: [
		 {
			name: 'Returns',
			data: general_graph_amount
   		 },
		 {
			name: 'Projection',
			data: general_graph_project_amount
   		 }, 
		 {
			name: 'Industry Average',
			data: general_graph_industry_average
		 }
			]
		});
				 }
					
					
			  }
		 }); 
	  
}
function resizable (el, factor) {
  var int = Number(factor) || 7.7;
  var int=11;
  function resize() {el.style.width = ((el.value.length+1) * int) + 'px';}
  var e = 'keyup,keypress,focus,blur,change'.split(',');
  for (var i in e) el.addEventListener(e[i],resize,false);
  resize();
}
resizable(document.getElementById('invest_assets'),7);
resizable(document.getElementById('invest_assets_year'),7);

</script>

