<div class="business_block">
	<div class="business_block_head">
    	<div class="business_block_head_text">
            <div class="head-one">TOGETHER WE CAN ACHIEVE MORE</div>
            <div class="head-two">LETS TALK BUSINESS</div>
            <div class="clearfix"><a class="head_join_btn">Join Now</a></div>
         </div>
    </div>
</div>

<div class="container support_company_box">
		<div class="col-lg-6 col-sm-7">
        	<div class="support_head">Welcome to the </div>
            <div class="support_head">Best Business </div>
            <div class="support_head">Support Company</div>
           
            <div class="service_text_box">
            <div class="service_text">
            	Economic services provided by the <br />finance industry, which encompasses a<br /> broad range of businesses that manage<br />
                money including credit unions.
            </div>
            </div>
            <div class="clearfix service_text_boxAbout" >
            	<a class="support_about">More About us</a>
            </div>
        </div >
        <div class="col-lg-6 col-sm-5">
        	<img src="<?php echo HTTP_IMG_PATH?>/business_company.png" class="img-responsive"  style="margin:0 auto;"/>
        </div>
</div>
<div class="clearfix">&nbsp;</div>
<div class="makediv" style="background-color: #f1f1f1;">
<div class="container">
	<div class="row">
    <div class="col-lg-4 col-sm-4 col-xs-12">
    	<div class="row stats_block">
        <div class="stats_block_top">
          <div class="stats_block_inner">
          <div class="stats_block_box_first">
          	<div class="stats_content">01</div>
           		<div class="stats_content_head">Make Business <br />Strategy</div>
             </div>
       		<div class="block_text_first"> We will help you set new business priorities, outline <br />plans for growth, determine a product roadmap or <br /> plan your investment decisions.</div>
            </div>
            </div>
        </div>
    </div>
    
    <div class="col-lg-4 col-sm-4 col-xs-12">
    	<div class="row stats_block stats_middle_block">
        <div class="stats_block_top">
          <div class="stats_block_inner">
          <div class="stats_block_box">
          	<div class="stats_content">02</div>
           		<div class="stats_content_head">Company of <br />Professionals</div>
             </div>
       		<div class="block_text"> Competence, Reliability, Honesty, Integrity – these definitions characterize our employees in the best way.</div>
            </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-4 col-xs-12">
    	<div class="row stats_block">
        <div class="stats_block_top">
          <div class="stats_block_inner">
          <div class="stats_block_box_last">
          	<div class="stats_content">03</div>
           		<div class="stats_content_head">We Love Our <br />Clients</div>
             </div>
       		<div class="block_text_last"> Success of any organization depends on customers. That is why the first rule of our business is to retain clients and build a loyal relationship with them.</div>
            </div>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>

<div class="makediv strate_box">
	<div class="strate_box_top">
    <div class="strate_box_top_inner">
           <div class="strate_box_top_panel">
            <div class="strate_box_top_head">our main goal –</div>
            <div class="strate_box_top_sub_head">Strategies That Work</div>
            <div class="strate_box_top_sub_text">
                Economic services provided by the finance industry, which encompasses a broad range of businesses that manage money, including credit unions.
            </div>
            <div><a class="find_out_btn">Find out more</a></div>
            </div>
    </div>
    </div>
</div>
<div class="makediv one-edge-shadow">

	<div class="col-lg-5 col-sm-6 " style="padding:0">
    		<div class="investment_block_left" >	
           
            <div class="investment_block_container">
            		<div class="investment_block_box">
            		<div class="investment_block_comt_head">Our commitment</div>
                    <div class="investment_block_comt_sub_head">The new way means we work for you.</div>
                    <div class="investment_block_comt_full_text">
                    	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                    </div>
                   
                    <div class="investment_out_btn_outer"><a class="investment_out_btn">Start your investment plan</a></div>
                    </div>
                </div>
            </div>
    </div>
    <div class="col-lg-7 col-sm-6" >
    		<div class="row investment_block">
            </div>
    </div>
</div>

<div class="makediv return_block text-center">
<div class="container">
	<div class="row">
	<div class="return_block_head">I would like to invest <span>5000 USD</span></div>
    <div class="return_block_sub_head">*Your Projected Returns are</div>
    <div class="text-center return_block_graph">
    	<img src="<?php echo HTTP_IMG_PATH?>/graph.png"  class="img-responsive" style=" margin: 0 auto;"/>
    </div>
    <div class="prospering_outer">
    	<a class="prospering_btn">Start Prospering</a>
    </div>
    
    <div class="prospering_bottom_txt">
    	*all projections are calculated using historical performance data, actual performance may vary
    </div>
    </div>
    </div>
</div>

